//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.TransferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://casham.com/esb/adapters/mdsetransfer/wsdl", ConfigurationName="TransferService.mdseTransferPort")]
    public interface mdseTransferPort {
        
        // CODEGEN: Generating message contract since the operation CreateRejectMissile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/MDSETransferAdapterService.serviceagent//Crea" +
            "teRejectMissile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.TransferService.CreateRejectMissileResponse CreateRejectMissile(Common.TransferService.CreateRejectMissileRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateVoidedMissile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/MDSETransferAdapterService.serviceagent//Crea" +
            "teVoidedMissile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.TransferService.CreateVoidedMissileResponse CreateVoidedMissile(Common.TransferService.CreateVoidedMissileRequest request);
        
        // CODEGEN: Generating message contract since the operation StoreToStoreTransferOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/MDSETransferAdapterService.serviceagent//Stor" +
            "eToStoreTransferOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.TransferService.StoreToStoreTransferOutResponse StoreToStoreTransferOut(Common.TransferService.StoreToStoreTransferOutRequest request);
        
        // CODEGEN: Generating message contract since the operation JSUPTransferOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/MDSETransferAdapterService.serviceagent//JSUP" +
            "TransferOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.TransferService.JSUPTransferOutResponse JSUPTransferOut(Common.TransferService.JSUPTransferOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class RJRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private RJRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RJRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class serviceInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainField;
        
        private endpointType sourceField;
        
        private string shopNumberField;
        
        private string terminalIDField;
        
        private string userIDField;
        
        private string transactionIDField;
        
        private System.DateTime timeStampField;
        
        private exceptionMessageType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public endpointType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string shopNumber {
            get {
                return this.shopNumberField;
            }
            set {
                this.shopNumberField = value;
                this.RaisePropertyChanged("shopNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string terminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("terminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public exceptionMessageType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class endpointType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string systemNameField;
        
        private string systemVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
                this.RaisePropertyChanged("systemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string systemVersion {
            get {
                return this.systemVersionField;
            }
            set {
                this.systemVersionField = value;
                this.RaisePropertyChanged("systemVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class JSUPReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private JSUPReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public JSUPReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class JSUPReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("status", typeof(string), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/cim/common/common_business_objects")]
    public partial class businessExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string descriptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class JSUPtransferType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeNumberField;
        
        private string transferNumberField;
        
        private string destinationField;
        
        private string transferTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string storeNumber {
            get {
                return this.storeNumberField;
            }
            set {
                this.storeNumberField = value;
                this.RaisePropertyChanged("storeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string transferNumber {
            get {
                return this.transferNumberField;
            }
            set {
                this.transferNumberField = value;
                this.RaisePropertyChanged("transferNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class JSUPRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private JSUPRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public JSUPRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class JSUPRequestTypeServiceData : serviceDataRequestType {
        
        private JSUPtransferType jSUPtransferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public JSUPtransferType JSUPtransfer {
            get {
                return this.jSUPtransferField;
            }
            set {
                this.jSUPtransferField = value;
                this.RaisePropertyChanged("JSUPtransfer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class storeToStoreReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private storeToStoreReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public storeToStoreReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class storeToStoreReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("status", typeof(string), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class transferType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeNumberField;
        
        private string transferNumberField;
        
        private string destinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string storeNumber {
            get {
                return this.storeNumberField;
            }
            set {
                this.storeNumberField = value;
                this.RaisePropertyChanged("storeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string transferNumber {
            get {
                return this.transferNumberField;
            }
            set {
                this.transferNumberField = value;
                this.RaisePropertyChanged("transferNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class storeToStoreRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private storeToStoreRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public storeToStoreRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class storeToStoreRequestTypeServiceData : serviceDataRequestType {
        
        private transferType transferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public transferType transfer {
            get {
                return this.transferField;
            }
            set {
                this.transferField = value;
                this.RaisePropertyChanged("transfer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class VMReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private VMReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VMReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class VMReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("status", typeof(string), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class VoidTransferType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeNumberField;
        
        private string transferNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string storeNumber {
            get {
                return this.storeNumberField;
            }
            set {
                this.storeNumberField = value;
                this.RaisePropertyChanged("storeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string transferNumber {
            get {
                return this.transferNumberField;
            }
            set {
                this.transferNumberField = value;
                this.RaisePropertyChanged("transferNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class VMRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private VMRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VMRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class VMRequestTypeServiceData : serviceDataRequestType {
        
        private VoidTransferType voidTransferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VoidTransferType VoidTransfer {
            get {
                return this.voidTransferField;
            }
            set {
                this.voidTransferField = value;
                this.RaisePropertyChanged("VoidTransfer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class RJReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private RJReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RJReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class RJReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("status", typeof(string), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class RejectTransferType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeNumberField;
        
        private string transferNumberField;
        
        private string rejectReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string storeNumber {
            get {
                return this.storeNumberField;
            }
            set {
                this.storeNumberField = value;
                this.RaisePropertyChanged("storeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string transferNumber {
            get {
                return this.transferNumberField;
            }
            set {
                this.transferNumberField = value;
                this.RaisePropertyChanged("transferNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string rejectReason {
            get {
                return this.rejectReasonField;
            }
            set {
                this.rejectReasonField = value;
                this.RaisePropertyChanged("rejectReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class userDefinedElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class exceptionMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionCodeField;
        
        private string sourceMessageField;
        
        private string subjectField;
        
        private System.DateTime dateTimestampField;
        
        private bool dateTimestampFieldSpecified;
        
        private string noteField;
        
        private endpointType originationField;
        
        private endpointType commonField;
        
        private endpointType destinationField;
        
        private string convertionIdField;
        
        private userDefinedElementType[] userDefinedElementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string exceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("exceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceMessage {
            get {
                return this.sourceMessageField;
            }
            set {
                this.sourceMessageField = value;
                this.RaisePropertyChanged("sourceMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime dateTimestamp {
            get {
                return this.dateTimestampField;
            }
            set {
                this.dateTimestampField = value;
                this.RaisePropertyChanged("dateTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimestampSpecified {
            get {
                return this.dateTimestampFieldSpecified;
            }
            set {
                this.dateTimestampFieldSpecified = value;
                this.RaisePropertyChanged("dateTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public endpointType origination {
            get {
                return this.originationField;
            }
            set {
                this.originationField = value;
                this.RaisePropertyChanged("origination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public endpointType common {
            get {
                return this.commonField;
            }
            set {
                this.commonField = value;
                this.RaisePropertyChanged("common");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public endpointType destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string convertionId {
            get {
                return this.convertionIdField;
            }
            set {
                this.convertionIdField = value;
                this.RaisePropertyChanged("convertionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userDefinedElements", Order=9)]
        public userDefinedElementType[] userDefinedElements {
            get {
                return this.userDefinedElementsField;
            }
            set {
                this.userDefinedElementsField = value;
                this.RaisePropertyChanged("userDefinedElements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/MDSETransfer")]
    public partial class RJRequestTypeServiceData : serviceDataRequestType {
        
        private RejectTransferType rejectTransferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RejectTransferType RejectTransfer {
            get {
                return this.rejectTransferField;
            }
            set {
                this.rejectTransferField = value;
                this.RaisePropertyChanged("RejectTransfer");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRejectMissileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.RJRequestType RJRequest;
        
        public CreateRejectMissileRequest() {
        }
        
        public CreateRejectMissileRequest(Common.TransferService.RJRequestType RJRequest) {
            this.RJRequest = RJRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRejectMissileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.RJReplyType RJReply;
        
        public CreateRejectMissileResponse() {
        }
        
        public CreateRejectMissileResponse(Common.TransferService.RJReplyType RJReply) {
            this.RJReply = RJReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateVoidedMissileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.VMRequestType VMRequest;
        
        public CreateVoidedMissileRequest() {
        }
        
        public CreateVoidedMissileRequest(Common.TransferService.VMRequestType VMRequest) {
            this.VMRequest = VMRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateVoidedMissileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.VMReplyType VMReply;
        
        public CreateVoidedMissileResponse() {
        }
        
        public CreateVoidedMissileResponse(Common.TransferService.VMReplyType VMReply) {
            this.VMReply = VMReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreToStoreTransferOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.storeToStoreRequestType storeToStoreRequest;
        
        public StoreToStoreTransferOutRequest() {
        }
        
        public StoreToStoreTransferOutRequest(Common.TransferService.storeToStoreRequestType storeToStoreRequest) {
            this.storeToStoreRequest = storeToStoreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreToStoreTransferOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.storeToStoreReplyType storeToStoreReply;
        
        public StoreToStoreTransferOutResponse() {
        }
        
        public StoreToStoreTransferOutResponse(Common.TransferService.storeToStoreReplyType storeToStoreReply) {
            this.storeToStoreReply = storeToStoreReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JSUPTransferOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.JSUPRequestType JSUPRequest;
        
        public JSUPTransferOutRequest() {
        }
        
        public JSUPTransferOutRequest(Common.TransferService.JSUPRequestType JSUPRequest) {
            this.JSUPRequest = JSUPRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JSUPTransferOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/MDSETransfer", Order=0)]
        public Common.TransferService.JSUPReplyType JSUPReply;
        
        public JSUPTransferOutResponse() {
        }
        
        public JSUPTransferOutResponse(Common.TransferService.JSUPReplyType JSUPReply) {
            this.JSUPReply = JSUPReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mdseTransferPortChannel : Common.TransferService.mdseTransferPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mdseTransferPortClient : System.ServiceModel.ClientBase<Common.TransferService.mdseTransferPort>, Common.TransferService.mdseTransferPort {
        
        public mdseTransferPortClient() {
        }
        
        public mdseTransferPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mdseTransferPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mdseTransferPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mdseTransferPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.TransferService.CreateRejectMissileResponse Common.TransferService.mdseTransferPort.CreateRejectMissile(Common.TransferService.CreateRejectMissileRequest request) {
            return base.Channel.CreateRejectMissile(request);
        }
        
        public Common.TransferService.RJReplyType CreateRejectMissile(Common.TransferService.RJRequestType RJRequest) {
            Common.TransferService.CreateRejectMissileRequest inValue = new Common.TransferService.CreateRejectMissileRequest();
            inValue.RJRequest = RJRequest;
            Common.TransferService.CreateRejectMissileResponse retVal = ((Common.TransferService.mdseTransferPort)(this)).CreateRejectMissile(inValue);
            return retVal.RJReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.TransferService.CreateVoidedMissileResponse Common.TransferService.mdseTransferPort.CreateVoidedMissile(Common.TransferService.CreateVoidedMissileRequest request) {
            return base.Channel.CreateVoidedMissile(request);
        }
        
        public Common.TransferService.VMReplyType CreateVoidedMissile(Common.TransferService.VMRequestType VMRequest) {
            Common.TransferService.CreateVoidedMissileRequest inValue = new Common.TransferService.CreateVoidedMissileRequest();
            inValue.VMRequest = VMRequest;
            Common.TransferService.CreateVoidedMissileResponse retVal = ((Common.TransferService.mdseTransferPort)(this)).CreateVoidedMissile(inValue);
            return retVal.VMReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.TransferService.StoreToStoreTransferOutResponse Common.TransferService.mdseTransferPort.StoreToStoreTransferOut(Common.TransferService.StoreToStoreTransferOutRequest request) {
            return base.Channel.StoreToStoreTransferOut(request);
        }
        
        public Common.TransferService.storeToStoreReplyType StoreToStoreTransferOut(Common.TransferService.storeToStoreRequestType storeToStoreRequest) {
            Common.TransferService.StoreToStoreTransferOutRequest inValue = new Common.TransferService.StoreToStoreTransferOutRequest();
            inValue.storeToStoreRequest = storeToStoreRequest;
            Common.TransferService.StoreToStoreTransferOutResponse retVal = ((Common.TransferService.mdseTransferPort)(this)).StoreToStoreTransferOut(inValue);
            return retVal.storeToStoreReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.TransferService.JSUPTransferOutResponse Common.TransferService.mdseTransferPort.JSUPTransferOut(Common.TransferService.JSUPTransferOutRequest request) {
            return base.Channel.JSUPTransferOut(request);
        }
        
        public Common.TransferService.JSUPReplyType JSUPTransferOut(Common.TransferService.JSUPRequestType JSUPRequest) {
            Common.TransferService.JSUPTransferOutRequest inValue = new Common.TransferService.JSUPTransferOutRequest();
            inValue.JSUPRequest = JSUPRequest;
            Common.TransferService.JSUPTransferOutResponse retVal = ((Common.TransferService.mdseTransferPort)(this)).JSUPTransferOut(inValue);
            return retVal.JSUPReply;
        }
    }
}
