//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pawn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Alarm {
            get {
                return ResourceManager.GetStream("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string AuditLogEnabled {
            get {
                return ResourceManager.GetString("AuditLogEnabled", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blue_border {
            get {
                object obj = ResourceManager.GetObject("blue_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blue_white_panel {
            get {
                object obj = ResourceManager.GetObject("blue_white_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossy_edit {
            get {
                object obj = ResourceManager.GetObject("blueglossy_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossy_edit_fixed {
            get {
                object obj = ResourceManager.GetObject("blueglossy_edit_fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossy_edit2 {
            get {
                object obj = ResourceManager.GetObject("blueglossy_edit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossy_select {
            get {
                object obj = ResourceManager.GetObject("blueglossy_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossy_select2 {
            get {
                object obj = ResourceManager.GetObject("blueglossy_select2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blueglossywhitebackground {
            get {
                object obj = ResourceManager.GetObject("blueglossywhitebackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cashdrawer {
            get {
                object obj = ResourceManager.GetObject("cashdrawer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CashlinxDesktop9a_3 {
            get {
                object obj = ResourceManager.GetObject("CashlinxDesktop9a_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dark_dialog_frame {
            get {
                object obj = ResourceManager.GetObject("dark_dialog_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DemoBackground {
            get {
                object obj = ResourceManager.GetObject("DemoBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap desktopUpperLeftPanel {
            get {
                object obj = ResourceManager.GetObject("desktopUpperLeftPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DP {
            get {
                object obj = ResourceManager.GetObject("DP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string ExceptionBoxEnabled {
            get {
                return ResourceManager.GetString("ExceptionBoxEnabled", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap HB {
            get {
                object obj = ResourceManager.GetObject("HB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HP {
            get {
                object obj = ResourceManager.GetObject("HP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string IntegratedCashDrawer {
            get {
                return ResourceManager.GetString("IntegratedCashDrawer", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string LoanInquiryMinimumCriteria {
            get {
                return ResourceManager.GetString("LoanInquiryMinimumCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string LogEnabled {
            get {
                return ResourceManager.GetString("LogEnabled", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo3 {
            get {
                object obj = ResourceManager.GetObject("logo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo31 {
            get {
                object obj = ResourceManager.GetObject("logo31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string MultipleLoanSelection {
            get {
                return ResourceManager.GetString("MultipleLoanSelection", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap newDialog_256_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_256_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_320_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_320_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_400_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_400_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_440_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_440_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_480_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_480_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_512_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_512_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_600_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_600_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_640_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_640_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newDialog_768_GreyScale {
            get {
                object obj = ResourceManager.GetObject("newDialog_768_GreyScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap oldvistabutton_blue {
            get {
                object obj = ResourceManager.GetObject("oldvistabutton_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OverrideMachineName {
            get {
                return ResourceManager.GetString("OverrideMachineName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Pearl {
            get {
                object obj = ResourceManager.GetObject("Pearl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99535a447a5ab36823bd6150acc267f9.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string SkipLDAP {
            get {
                return ResourceManager.GetString("SkipLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aagent.
        /// </summary>
        public static string SkipLDAPDisplayName {
            get {
                return ResourceManager.GetString("SkipLDAPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aagent.
        /// </summary>
        public static string SkipLDAPUserName {
            get {
                return ResourceManager.GetString("SkipLDAPUserName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap TenderTypeBorder {
            get {
                object obj = ResourceManager.GetObject("TenderTypeBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string UseDevMD5Key {
            get {
                return ResourceManager.GetString("UseDevMD5Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string USPSValidationEnabled {
            get {
                return ResourceManager.GetString("USPSValidationEnabled", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap vistabutton_blue {
            get {
                object obj = ResourceManager.GetObject("vistabutton_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vistabutton_crop {
            get {
                object obj = ResourceManager.GetObject("vistabutton_crop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vistabutton_rollover_crop {
            get {
                object obj = ResourceManager.GetObject("vistabutton_rollover_crop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vistabutton_rollover_shadow_cropped1 {
            get {
                object obj = ResourceManager.GetObject("vistabutton_rollover_shadow_cropped1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vistabutton_shadow {
            get {
                object obj = ResourceManager.GetObject("vistabutton_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Warp {
            get {
                return ResourceManager.GetStream("Warp", resourceCulture);
            }
        }
    }
}
