//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawnUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PawnUtilities.Properties.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer should be at least 18 years of age.
        /// </summary>
        internal static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to Extend cannot be less than the daily amount.
        /// </summary>
        internal static string AmountToExtendLessThanDailyAmt {
            get {
                return ResourceManager.GetString("AmountToExtendLessThanDailyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to Extend cannot be less than the monthly amount.
        /// </summary>
        internal static string AmountToExtendLessThanMonthlyAmount {
            get {
                return ResourceManager.GetString("AmountToExtendLessThanMonthlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to extend has been updated to be exact multiple of daily amount..
        /// </summary>
        internal static string AmountToExtendMoreThanDailyAmt {
            get {
                return ResourceManager.GetString("AmountToExtendMoreThanDailyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to extend has been updated to be exact multiple of monthly amount..
        /// </summary>
        internal static string AmountToExtendMoreThanMonthlyAmt {
            get {
                return ResourceManager.GetString("AmountToExtendMoreThanMonthlyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This loan is ineligible for service due to a Bankruptcy Hold. Please Call CAI Legal services with any questions..
        /// </summary>
        internal static string BankruptcyHoldPickupIneligibleMsg {
            get {
                return ResourceManager.GetString("BankruptcyHoldPickupIneligibleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the data entered will be lost. Do you wish to cancel?.
        /// </summary>
        internal static string CancelConfirmMessage {
            get {
                return ResourceManager.GetString("CancelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Area code is  not entered but a phone number is entered..
        /// </summary>
        internal static string CellAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("CellAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone number cannot be blank if area code is entered.
        /// </summary>
        internal static string CellNumberNotEnteredError {
            get {
                return ResourceManager.GetString("CellNumberNotEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments cannot be empty.
        /// </summary>
        internal static string CommentsEmptyMessage {
            get {
                return ResourceManager.GetString("CommentsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch eye color data from session instance.
        /// </summary>
        internal static string CountryDataFetchError {
            get {
                return ResourceManager.GetString("CountryDataFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country data could not be populated.
        /// </summary>
        internal static string CountryNoData {
            get {
                return ResourceManager.GetString("CountryNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing comments failed. Please retry or cancel. .
        /// </summary>
        internal static string CustCommentsUpdateFailure {
            get {
                return ResourceManager.GetString("CustCommentsUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer contact info details failed. Please retry or cancel.
        /// </summary>
        internal static string CustContactInfoUpdateFailure {
            get {
                return ResourceManager.GetString("CustContactInfoUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated contact information.
        /// </summary>
        internal static string CustContactInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("CustContactInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer successfully created.
        /// </summary>
        internal static string CustCreationSuccess {
            get {
                return ResourceManager.GetString("CustCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Data could not be added. Please retry or cancel..
        /// </summary>
        internal static string CustDataAddFailure {
            get {
                return ResourceManager.GetString("CustDataAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transactions Found.
        /// </summary>
        internal static string CustHoldsNoTransactions {
            get {
                return ResourceManager.GetString("CustHoldsNoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Identification Primary Flag Failed. Please retry or cancel.
        /// </summary>
        internal static string CustIdentPrimaryFlagUpdateFailure {
            get {
                return ResourceManager.GetString("CustIdentPrimaryFlagUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new Customer Identification Failed. Please retry or cancel.
        /// </summary>
        internal static string CustIdentUpdateFailure {
            get {
                return ResourceManager.GetString("CustIdentUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the new Identification data for the customer.
        /// </summary>
        internal static string CustIdentUpdateSuccess {
            get {
                return ResourceManager.GetString("CustIdentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Mailing Address Failed. Please retry or cancel..
        /// </summary>
        internal static string CustMailingAddrUpdateFail {
            get {
                return ResourceManager.GetString("CustMailingAddrUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not meet the age criteria for firearm transactions. This Loan can not be Picked up..
        /// </summary>
        internal static string CustomerFirearmMessage {
            get {
                return ResourceManager.GetString("CustomerFirearmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Personal Information Failed. Please retry or cancel.
        /// </summary>
        internal static string CustPersInfoUpdateFailure {
            get {
                return ResourceManager.GetString("CustPersInfoUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated customer personal information.
        /// </summary>
        internal static string CustPersInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("CustPersInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Phone details Failed. Please retry or cancel.
        /// </summary>
        internal static string CustPhoneUpdateFailure {
            get {
                return ResourceManager.GetString("CustPhoneUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated phone details for the customer.
        /// </summary>
        internal static string CustPhoneUpdateSuccess {
            get {
                return ResourceManager.GetString("CustPhoneUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Physical Address Failed. Please retry or cancel..
        /// </summary>
        internal static string CustPhysicalAddrUpdateFail {
            get {
                return ResourceManager.GetString("CustPhysicalAddrUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Physical Description Failed. Please retry or cancel.
        /// </summary>
        internal static string CustPhysicalDescUpdateFailure {
            get {
                return ResourceManager.GetString("CustPhysicalDescUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated personal description of the customer.
        /// </summary>
        internal static string CustPhysicalDescUpdateSuccess {
            get {
                return ResourceManager.GetString("CustPhysicalDescUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer Work Address Failed. Please retry or cancel..
        /// </summary>
        internal static string CustWorkAddrUpdateFail {
            get {
                return ResourceManager.GetString("CustWorkAddrUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Government Identification you submitted is associated to another customer.
        /// </summary>
        internal static string DuplicateIDMessage {
            get {
                return ResourceManager.GetString("DuplicateIDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identification you entered already exists for this customer.
        /// </summary>
        internal static string DuplicateIDSameCustomer {
            get {
                return ResourceManager.GetString("DuplicateIDSameCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identification you entered already exists for this customer but with a different expiration date. Update that identification with this expiration date..
        /// </summary>
        internal static string DuplicateIDSameCustomerDiffExpiryDt {
            get {
                return ResourceManager.GetString("DuplicateIDSameCustomerDiffExpiryDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name and date of birth are associated to another customer. Do you want to continue?.
        /// </summary>
        internal static string DuplicateNameMessage {
            get {
                return ResourceManager.GetString("DuplicateNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Social Security Number already exists with someone&apos;s name. Please Check Number Again.
        /// </summary>
        internal static string DuplicateSSNMessage {
            get {
                return ResourceManager.GetString("DuplicateSSNMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Master Cash Drawer cannot be balanced until all cash drawers are closed. The following cash drawers are still open: .
        /// </summary>
        internal static string EM01CloseCashDrawers {
            get {
                return ResourceManager.GetString("EM01CloseCashDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous day&apos;s shop cash was not verified. The safe must be balanced before this transaction can be completed..
        /// </summary>
        internal static string EM03BalanceSafe {
            get {
                return ResourceManager.GetString("EM03BalanceSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous day&apos;s cash for all drawers must be verified to balance the safe. The following Drawers must be balanced :.
        /// </summary>
        internal static string EM05CDClosedUnverified {
            get {
                return ResourceManager.GetString("EM05CDClosedUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more shop transfers pending. Do you want to continue?.
        /// </summary>
        internal static string EM07ShopTransferPending {
            get {
                return ResourceManager.GetString("EM07ShopTransferPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entered Customer&apos;s Information is associated to an Existing Customer.
        /// </summary>
        internal static string ExistingCustomerHeader {
            get {
                return ResourceManager.GetString("ExistingCustomerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day to Pickup updated to next valid date.
        /// </summary>
        internal static string ExtendDateAdjustedMessage {
            get {
                return ResourceManager.GetString("ExtendDateAdjustedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day to pickup cannot be less than the current pickup date.
        /// </summary>
        internal static string ExtensionPickupDateError {
            get {
                return ResourceManager.GetString("ExtensionPickupDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Area Code is not entered but a number is entered..
        /// </summary>
        internal static string FaxAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("FaxAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number cannot be blank if area code is entered..
        /// </summary>
        internal static string FaxNumberNotEnteredError {
            get {
                return ResourceManager.GetString("FaxNumberNotEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the errors in the form and submit again.
        /// </summary>
        internal static string FormErrorSubmitAgain {
            get {
                return ResourceManager.GetString("FormErrorSubmitAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partial address cannot be entered..
        /// </summary>
        internal static string FormPartialAddressEntered {
            get {
                return ResourceManager.GetString("FormPartialAddressEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the required fields in the form and submit.
        /// </summary>
        internal static string FormRequiredFieldsFilledError {
            get {
                return ResourceManager.GetString("FormRequiredFieldsFilledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gun record cannot be edited. Please call Firearm Compliance..
        /// </summary>
        internal static string GunEditError {
            get {
                return ResourceManager.GetString("GunEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gun record cannot be edited. Please contact Support for further
        ///assistance.
        /// </summary>
        internal static string GunEditErrorMessage {
            get {
                return ResourceManager.GetString("GunEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Area code is not entered but a phone number is entered. .
        /// </summary>
        internal static string HomeAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("HomeAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone number cannot be blank if area code is entered.
        /// </summary>
        internal static string HomeNumberNotEnteredError {
            get {
                return ResourceManager.GetString("HomeNumberNotEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICN# entered is not a valid number. Please try again..
        /// </summary>
        internal static string ICNInvalid {
            get {
                return ResourceManager.GetString("ICNInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Issuer cannot be left blank.
        /// </summary>
        internal static string IDIssuerRequired {
            get {
                return ResourceManager.GetString("IDIssuerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Continue with Existing Customer or Update his/her information or Select the new customer and go Back to update the ID Information.
        /// </summary>
        internal static string IDMatchMessage {
            get {
                return ResourceManager.GetString("IDMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number cannot be left blank.
        /// </summary>
        internal static string IDNumberRequired {
            get {
                return ResourceManager.GetString("IDNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either date of birth or identification for the customer..
        /// </summary>
        internal static string IDorDOBEnterMessage {
            get {
                return ResourceManager.GetString("IDorDOBEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type and ID Issuer cannot be left blank.
        /// </summary>
        internal static string IDTypeAndIssuerRequired {
            get {
                return ResourceManager.GetString("IDTypeAndIssuerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type cannot be left blank.
        /// </summary>
        internal static string IDTypeRequired {
            get {
                return ResourceManager.GetString("IDTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ticket number is inactive. Please refer to Customer History..
        /// </summary>
        internal static string InactiveTicketMessage {
            get {
                return ResourceManager.GetString("InactiveTicketMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount entered..
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount to extend entered.
        /// </summary>
        internal static string InvalidAmountToExtend {
            get {
                return ResourceManager.GetString("InvalidAmountToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date entered..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date of Birth entered..
        /// </summary>
        internal static string InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Days to extend entered.
        /// </summary>
        internal static string InvalidDaysToExtend {
            get {
                return ResourceManager.GetString("InvalidDaysToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address format is not correct.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in Feet should be a number from 2 to 9.
        /// </summary>
        internal static string InvalidHeightFeet {
            get {
                return ResourceManager.GetString("InvalidHeightFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches can only be a number between 1 and 11.
        /// </summary>
        internal static string InvalidHeightInches {
            get {
                return ResourceManager.GetString("InvalidHeightInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Months to extend entered.
        /// </summary>
        internal static string InvalidMonthsToExtend {
            get {
                return ResourceManager.GetString("InvalidMonthsToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code should be a 3 digit number.
        /// </summary>
        internal static string InvalidPhoneAreaCode {
            get {
                return ResourceManager.GetString("InvalidPhoneAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number should be a 7 digit number.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SSN entered..
        /// </summary>
        internal static string InvalidSSN {
            get {
                return ResourceManager.GetString("InvalidSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ticket Number. Please Enter Again!!!.
        /// </summary>
        internal static string InvalidTicketMessage {
            get {
                return ResourceManager.GetString("InvalidTicketMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas Driver&apos;s License should have 8 digits.
        /// </summary>
        internal static string InvalidTXLicense {
            get {
                return ResourceManager.GetString("InvalidTXLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can only be a number from 1 to 999.
        /// </summary>
        internal static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Number could not be generated. Customer information was saved. Please Retry or Cancel.
        /// </summary>
        internal static string LoanIdCreationError {
            get {
                return ResourceManager.GetString("LoanIdCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is locked for PFI processing. Please try again later.
        /// </summary>
        internal static string LockedRecordMessage {
            get {
                return ResourceManager.GetString("LockedRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Customer number to search.
        /// </summary>
        internal static string LookupCustNumberError {
            get {
                return ResourceManager.GetString("LookupCustNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 2 criteria should be selected for searching using customer Information.
        /// </summary>
        internal static string LookupFormCriteriaError {
            get {
                return ResourceManager.GetString("LookupFormCriteriaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Search requires ID Type, ID Number and ID Issuer.
        /// </summary>
        internal static string LookupIDError {
            get {
                return ResourceManager.GetString("LookupIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer Loan Number for the search.
        /// </summary>
        internal static string LookupLoanNumberError {
            get {
                return ResourceManager.GetString("LookupLoanNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number entered.
        /// </summary>
        internal static string LookupPhoneNumberError {
            get {
                return ResourceManager.GetString("LookupPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in lookup search results screen.
        /// </summary>
        internal static string LookupResultsExceptionError {
            get {
                return ResourceManager.GetString("LookupResultsExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a search criteria and submit.
        /// </summary>
        internal static string LookupSearchCriteriaError {
            get {
                return ResourceManager.GetString("LookupSearchCriteriaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan redemption transactions by a person who is not the pledgor must be accompanied by the customer&apos;s copy of the pawn ticket.
        /// </summary>
        internal static string LookupTicketContinuePromptMsg {
            get {
                return ResourceManager.GetString("LookupTicketContinuePromptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid/In-Active Ticket.
        /// </summary>
        internal static string LookupTicketInvalidMessage {
            get {
                return ResourceManager.GetString("LookupTicketInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number associated with the loan is invalid. Please retry or cancel..
        /// </summary>
        internal static string LookupTicketNoCustomerMessage {
            get {
                return ResourceManager.GetString("LookupTicketNoCustomerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Number cannot be empty.
        /// </summary>
        internal static string LookupTicketStoreNumberMsg {
            get {
                return ResourceManager.GetString("LookupTicketStoreNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number cannot be empty and should at least have 3 digits.
        /// </summary>
        internal static string LookupTicketTicketNumberMsg {
            get {
                return ResourceManager.GetString("LookupTicketTicketNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Vendor Name to search.
        /// </summary>
        internal static string LookupVendorNameError {
            get {
                return ResourceManager.GetString("LookupVendorNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Tax ID to search.
        /// </summary>
        internal static string LookupVendorTaxIDError {
            get {
                return ResourceManager.GetString("LookupVendorTaxIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For wild card search please make sure to enter a minimum of three characters in either First Name or Last Name.
        /// </summary>
        internal static string LookupWildcardsearchErrorMsg {
            get {
                return ResourceManager.GetString("LookupWildcardsearchErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Authorization Required.
        /// </summary>
        internal static string ManageOverrideDefaultMessage {
            get {
                return ResourceManager.GetString("ManageOverrideDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the recommended loan amount by $.
        /// </summary>
        internal static string ManageOverrideDescMercMsg2 {
            get {
                return ResourceManager.GetString("ManageOverrideDescMercMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this item is less than.
        /// </summary>
        internal static string ManageOverrideDescMercMsgLess {
            get {
                return ResourceManager.GetString("ManageOverrideDescMercMsgLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this item is more than.
        /// </summary>
        internal static string ManageOverrideDescMercMsgMore {
            get {
                return ResourceManager.GetString("ManageOverrideDescMercMsgMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan amount of $.
        /// </summary>
        internal static string ManageOverrideLoanMsg {
            get {
                return ResourceManager.GetString("ManageOverrideLoanMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is over your authorized limit!.
        /// </summary>
        internal static string ManageOverrideLoanMsg2 {
            get {
                return ResourceManager.GetString("ManageOverrideLoanMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login - check the user name and password and try again.
        /// </summary>
        internal static string ManageOverrideLoginFailed {
            get {
                return ResourceManager.GetString("ManageOverrideLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager&apos;s Authorization Required.
        /// </summary>
        internal static string ManageOverrideMgrMsg {
            get {
                return ResourceManager.GetString("ManageOverrideMgrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan is being PFIed!.
        /// </summary>
        internal static string ManageOverridePFIMsg {
            get {
                return ResourceManager.GetString("ManageOverridePFIMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buy amount of $.
        /// </summary>
        internal static string ManageOverridePurchaseMsg {
            get {
                return ResourceManager.GetString("ManageOverridePurchaseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is over your authorized limit!.
        /// </summary>
        internal static string ManageOverridePurchaseMsg2 {
            get {
                return ResourceManager.GetString("ManageOverridePurchaseMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to perform override.
        /// </summary>
        internal static string ManageOverrideUsernotAllowerd {
            get {
                return ResourceManager.GetString("ManageOverrideUsernotAllowerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active customer in session..
        /// </summary>
        internal static string MissingCustData {
            get {
                return ResourceManager.GetString("MissingCustData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found over 15 customer records. Please refine the search and search again or select a customer to view..
        /// </summary>
        internal static string MultipleCustSearchResults {
            get {
                return ResourceManager.GetString("MultipleCustSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found over 15 vendor records. Please refine the search and search again or select a customer to view..
        /// </summary>
        internal static string MultipleVendSearchResults {
            get {
                return ResourceManager.GetString("MultipleVendSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Continue with Existing Customer or Update his/her information or Select the new customer and continue to add as new customer.
        /// </summary>
        internal static string NameMatchMessage {
            get {
                return ResourceManager.GetString("NameMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were done in the form for update..
        /// </summary>
        internal static string NoChangesInForm {
            get {
                return ResourceManager.GetString("NoChangesInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lost ticket loans to process..
        /// </summary>
        internal static string NoLostTicketLoans {
            get {
                return ResourceManager.GetString("NoLostTicketLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Documentation Required.
        /// </summary>
        internal static string OverrideReasonLegalDoc {
            get {
                return ResourceManager.GetString("OverrideReasonLegalDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Pick up using out of state ID.
        /// </summary>
        internal static string OverrideReasonOutOfStateID {
            get {
                return ResourceManager.GetString("OverrideReasonOutOfStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible for PFI.
        /// </summary>
        internal static string OverrideReasonPFIEligible {
            get {
                return ResourceManager.GetString("OverrideReasonPFIEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFI In Process.
        /// </summary>
        internal static string OverrideReasonPFIInProcess {
            get {
                return ResourceManager.GetString("OverrideReasonPFIInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan has existing Police Hold..
        /// </summary>
        internal static string OverrideReasonPoliceHold {
            get {
                return ResourceManager.GetString("OverrideReasonPoliceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager Area Code is not entered but a number is entered..
        /// </summary>
        internal static string PagerAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("PagerAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager Number cannot be blank if area code is entered..
        /// </summary>
        internal static string PagerNumberNotEnteredError {
            get {
                return ResourceManager.GetString("PagerNumberNotEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not eligible for Pawn Loan.
        /// </summary>
        internal static string PawnLoanAgeError {
            get {
                return ResourceManager.GetString("PawnLoanAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone area code is not entered but a phone number is entered. .
        /// </summary>
        internal static string PhoneAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("PhoneAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get picklist details.
        /// </summary>
        internal static string PicklistNoData {
            get {
                return ResourceManager.GetString("PicklistNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notarized Authorization from the pledgor is required to redeem this loan..
        /// </summary>
        internal static string PickupLegalDocRequiredMsg {
            get {
                return ResourceManager.GetString("PickupLegalDocRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the selected Transactions need manager override but the override did not happen. Cannot proceed with pickup.
        /// </summary>
        internal static string PickupOverrideFailedMessage {
            get {
                return ResourceManager.GetString("PickupOverrideFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This loan is ineligible for pickup due to a Police Hold. Please see Store Manager for details..
        /// </summary>
        internal static string PoliceHoldPickupIneligibleMsg {
            get {
                return ResourceManager.GetString("PoliceHoldPickupIneligibleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not entered for phone type selected as primary. Do you wish to continue?.
        /// </summary>
        internal static string PrimaryPhoneError {
            get {
                return ResourceManager.GetString("PrimaryPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in processing your request. Please try again or cancel.
        /// </summary>
        internal static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information needed to process lost pawn ticket fee is not available.
        /// </summary>
        internal static string ProcessLostPawnTktNoCustLoans {
            get {
                return ResourceManager.GetString("ProcessLostPawnTktNoCustLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the loan to set the ticket as lost. Please retry or cancel..
        /// </summary>
        internal static string ProcessLostTktFeeError {
            get {
                return ResourceManager.GetString("ProcessLostTktFeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firearm Background check failed. Cannot proceed with return..
        /// </summary>
        internal static string PurchaseReturnFirearmMessage {
            get {
                return ResourceManager.GetString("PurchaseReturnFirearmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiving the indicated  fee(s) will cause the new loan to fall below the minimum amount required.
        /// </summary>
        internal static string RollOverWaiveFeeMessage {
            get {
                return ResourceManager.GetString("RollOverWaiveFeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the selected customer from search results.
        /// </summary>
        internal static string SelectedCustomerLoadError {
            get {
                return ResourceManager.GetString("SelectedCustomerLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the selected vendor from search results.
        /// </summary>
        internal static string SelectedVendorLoadError {
            get {
                return ResourceManager.GetString("SelectedVendorLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Social Security Number entered..
        /// </summary>
        internal static string SSNError {
            get {
                return ResourceManager.GetString("SSNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the number of Bar Code Tags to reprint..
        /// </summary>
        internal static string TagReprintBarCodePrintNumber {
            get {
                return ResourceManager.GetString("TagReprintBarCodePrintNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short code entered is a duplicate. Please make your selection from the list..
        /// </summary>
        internal static string TagReprintDuplicateShortCodeMsg {
            get {
                return ResourceManager.GetString("TagReprintDuplicateShortCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Print Features Tag msut be &quot;Y&quot; or &quot;N&quot;..
        /// </summary>
        internal static string TagReprintFeatureTagMsg {
            get {
                return ResourceManager.GetString("TagReprintFeatureTagMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICN# entered is not a valid number. Please try again..
        /// </summary>
        internal static string TagReprintIcnNumberInvalid {
            get {
                return ResourceManager.GetString("TagReprintIcnNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid records found.  Please enter another number..
        /// </summary>
        internal static string TagReprintIcnNumberMsg {
            get {
                return ResourceManager.GetString("TagReprintIcnNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select ICN number for the Bar Code Tag reprint..
        /// </summary>
        internal static string TagReprintSelectIcnNumberMsg {
            get {
                return ResourceManager.GetString("TagReprintSelectIcnNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan marked for Extend.
        /// </summary>
        internal static string TempStatusExtend {
            get {
                return ResourceManager.GetString("TempStatusExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan in PFI Processing.
        /// </summary>
        internal static string TempStatusPFI {
            get {
                return ResourceManager.GetString("TempStatusPFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan marked for Pickup.
        /// </summary>
        internal static string TempStatusPickup {
            get {
                return ResourceManager.GetString("TempStatusPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan marked for Rollover.
        /// </summary>
        internal static string TempStatusRollover {
            get {
                return ResourceManager.GetString("TempStatusRollover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ticket number entered was not valid.  Please try again..
        /// </summary>
        internal static string TicketInvalid {
            get {
                return ResourceManager.GetString("TicketInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a cash drawer..
        /// </summary>
        internal static string UniqueCashDrawer {
            get {
                return ResourceManager.GetString("UniqueCashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue with the others?.
        /// </summary>
        internal static string ValidationForServicesFailedMessage {
            get {
                return ResourceManager.GetString("ValidationForServicesFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify all information and select or enter the customer&apos;s identification to pickup firearm..
        /// </summary>
        internal static string ViewCustProdDetailsFirearmMsg {
            get {
                return ResourceManager.GetString("ViewCustProdDetailsFirearmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop credit from layaway forfeiture has been used. Cannot void forfeiture.
        /// </summary>
        internal static string VoidForfeitureFailure {
            get {
                return ResourceManager.GetString("VoidForfeitureFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Manager&apos;s Authorization is required to Waive/Prorate Fees.
        /// </summary>
        internal static string WaiveFeesOverrideMessage {
            get {
                return ResourceManager.GetString("WaiveFeesOverrideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are cash drawers open at this time. Is this a trial balance?.
        /// </summary>
        internal static string WF01OpenCashDrawers {
            get {
                return ResourceManager.GetString("WF01OpenCashDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction will require you to rebalance drawer.
        /// </summary>
        internal static string WM02RebalanceDrawerRequired {
            get {
                return ResourceManager.GetString("WM02RebalanceDrawerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone Area code is not entered but a phone number is entered. .
        /// </summary>
        internal static string WorkAreaCodeNotEntered {
            get {
                return ResourceManager.GetString("WorkAreaCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work phone number cannot be blank if area code is entered.
        /// </summary>
        internal static string WorkNumberNotEnteredError {
            get {
                return ResourceManager.GetString("WorkNumberNotEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items for Ticket Number Entered are not in this store, but are in store #.
        /// </summary>
        internal static string WrongStore {
            get {
                return ResourceManager.GetString("WrongStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search resulted in 0 records for.
        /// </summary>
        internal static string ZeroCustSearchResults {
            get {
                return ResourceManager.GetString("ZeroCustSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days to extend cannot be less than 0.
        /// </summary>
        internal static string ZeroDaysToExtendError {
            get {
                return ResourceManager.GetString("ZeroDaysToExtendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Months to extend cannot be less than 0.
        /// </summary>
        internal static string ZeroMonthsToExtendError {
            get {
                return ResourceManager.GetString("ZeroMonthsToExtendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search resulted in 0 records for.
        /// </summary>
        internal static string ZeroVendSearchResults {
            get {
                return ResourceManager.GetString("ZeroVendSearchResults", resourceCulture);
            }
        }
    }
}
