//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static System.Drawing.Bitmap back_button_depressed
        {
            get
            {
                object obj = ResourceManager.GetObject("back_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap back_button_disabled
        {
            get
            {
                object obj = ResourceManager.GetObject("back_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap back_button_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("back_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap back_button_normal
        {
            get
            {
                object obj = ResourceManager.GetObject("back_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blueglossy_edit_fixed
        {
            get
            {
                object obj = ResourceManager.GetObject("blueglossy_edit_fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blueglossy_select
        {
            get
            {
                object obj = ResourceManager.GetObject("blueglossy_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blueglossy_select2
        {
            get
            {
                object obj = ResourceManager.GetObject("blueglossy_select2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blueglossy_small
        {
            get
            {
                object obj = ResourceManager.GetObject("blueglossy_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blueglossy_tiny
        {
            get
            {
                object obj = ResourceManager.GetObject("blueglossy_tiny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap bluerectangleglossy
        {
            get
            {
                object obj = ResourceManager.GetObject("bluerectangleglossy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Button_Refresh_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Button_Refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap calendar_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("calendar_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ns0:categoryList xmlns:ns0=&quot;http://casham.com/esb/adapters/proknow&quot;&gt;
        ///    &lt;ns0:childCat&gt;
        ///        &lt;ns0:catCode&gt;1000&lt;/ns0:catCode&gt;
        ///        &lt;ns0:catCode1&gt;1&lt;/ns0:catCode1&gt;
        ///        &lt;ns0:catCode2&gt;0&lt;/ns0:catCode2&gt;
        ///        &lt;ns0:catCode3&gt;0&lt;/ns0:catCode3&gt;
        ///        &lt;ns0:catCode4&gt;0&lt;/ns0:catCode4&gt;
        ///        &lt;ns0:catMaskPointer&gt;1000&lt;/ns0:catMaskPointer&gt;
        ///        &lt;ns0:catComplete&gt;N&lt;/ns0:catComplete&gt;
        ///        &lt;ns0:catAllowed&gt;Y&lt;/ns0:catAllowed&gt;
        ///        &lt;ns0:catDescription&gt;JEWELRY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string category
        {
            get
            {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap cl1
        {
            get
            {
                object obj = ResourceManager.GetObject("cl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl11
        {
            get
            {
                object obj = ResourceManager.GetObject("cl11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl2
        {
            get
            {
                object obj = ResourceManager.GetObject("cl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl21
        {
            get
            {
                object obj = ResourceManager.GetObject("cl21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl3
        {
            get
            {
                object obj = ResourceManager.GetObject("cl3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl31
        {
            get
            {
                object obj = ResourceManager.GetObject("cl31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl4
        {
            get
            {
                object obj = ResourceManager.GetObject("cl4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl41
        {
            get
            {
                object obj = ResourceManager.GetObject("cl41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl5
        {
            get
            {
                object obj = ResourceManager.GetObject("cl5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap cl51
        {
            get
            {
                object obj = ResourceManager.GetObject("cl51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Collapsed
        {
            get
            {
                object obj = ResourceManager.GetObject("Collapsed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap dark_dialog_frame
        {
            get
            {
                object obj = ResourceManager.GetObject("dark_dialog_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap exitbutton
        {
            get
            {
                object obj = ResourceManager.GetObject("exitbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Expanded
        {
            get
            {
                object obj = ResourceManager.GetObject("Expanded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;STX&gt;R&lt;ETX&gt;
        ///&lt;STX&gt;&lt;ESC&gt;c&lt;ETX&gt;
        ///&lt;STX&gt;&lt;ESC&gt;P&lt;ETX&gt;
        ///&lt;STX&gt;G1,cash;x21;y25;&lt;ETX&gt;
        ///&lt;STX&gt;u00,0001000000000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u01,0001100000000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u02,0001110000000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u03,0001111000000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u04,0001111100000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u05,0100111110000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u06,0110011111000000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u07,0011001111100000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u08,0001100111110000000000000;&lt;ETX&gt;
        ///&lt;STX&gt;u09,0000110011111111111111111;&lt;ETX&gt;
        ///&lt;STX&gt;u10,000001 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IPL_Print_Formats
        {
            get
            {
                return ResourceManager.GetString("IPL_Print_Formats", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap logo
        {
            get
            {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap logoCasham
        {
            get
            {
                object obj = ResourceManager.GetObject("logoCasham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap logoCashlinx
        {
            get
            {
                object obj = ResourceManager.GetObject("logoCashlinx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap metal_button_green_small
        {
            get
            {
                object obj = ResourceManager.GetObject("metal_button_green_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap metal_button_red_small
        {
            get
            {
                object obj = ResourceManager.GetObject("metal_button_red_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap metal_button_yellow_small
        {
            get
            {
                object obj = ResourceManager.GetObject("metal_button_yellow_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap minus_icon_small
        {
            get
            {
                object obj = ResourceManager.GetObject("minus_icon_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap mutebutton
        {
            get
            {
                object obj = ResourceManager.GetObject("mutebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap mutebuttondepressed
        {
            get
            {
                object obj = ResourceManager.GetObject("mutebuttondepressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_320_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_320_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_400_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_400_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_440_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_440_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_480_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_480_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_512_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_512_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_600_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_600_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap newDialog_768_BlueScale
        {
            get
            {
                object obj = ResourceManager.GetObject("newDialog_768_BlueScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap pausebutton
        {
            get
            {
                object obj = ResourceManager.GetObject("pausebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap pausebuttondepressed
        {
            get
            {
                object obj = ResourceManager.GetObject("pausebuttondepressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap pdf_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("pdf_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap playbutton
        {
            get
            {
                object obj = ResourceManager.GetObject("playbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap playbutton1
        {
            get
            {
                object obj = ResourceManager.GetObject("playbutton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap playbuttondepressed
        {
            get
            {
                object obj = ResourceManager.GetObject("playbuttondepressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap plus_icon_small
        {
            get
            {
                object obj = ResourceManager.GetObject("plus_icon_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 99535a447a5ab36823bd6150acc267f9.
        /// </summary>
        public static string PrivateKey
        {
            get
            {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap receipt_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("receipt_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap refresh_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EDITCUSTINFO=EditCustInfo
        ///UPDATESSN=UpdateSSN
        ///PHYSICALDESCRIPTION=View PhysicalDescriptionTab
        ///EDITPHYSICALDESCRIPTION=Edit PhysicalDescriptionTab
        ///EDITGOVTIDTYPEAGENCY=EditGovtIDTypeAgency
        ///EDITGOVTIDNUMBER=EditGovtIDNumber
        ///OVERRIDE=Override
        ///NEWPAWNLOAN=NewPawnLoan
        ///EDITCOMMENTS=EditComments
        ///SERVICES=Services
        ///BUY OUT=Buy Out
        ///BANKRUPTCYHOLD=BankruptcyHold
        ///CUSTOMERHOLDS=CustomerHold
        ///PFICREATELIST=CreatePFIListPanel
        ///PFIVERIFY=PFIVerifyPanel
        ///PFIPOST=PostPFIActivityPanel
        ///CHARGEOFF=ChargeOff
        ///POLICE_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResourceNames
        {
            get
            {
                return ResourceManager.GetString("ResourceNames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///    &lt;Section Value=&apos;ROLE_HIERARCHY&apos;&gt;
        ///        &lt;Role&gt;
        ///            &lt;Tag&gt;CSR1&lt;/Tag&gt;
        ///            &lt;Value type=&apos;Level&apos;&gt;1&lt;/Value&gt;
        ///        &lt;/Role&gt;
        ///        &lt;Role&gt;
        ///            &lt;Tag&gt;CSR2&lt;/Tag&gt;
        ///            &lt;Value type=&apos;Level&apos;&gt;1&lt;/Value&gt;
        ///        &lt;/Role&gt;
        ///        &lt;Role&gt;
        ///            &lt;Tag&gt;CSR3&lt;/Tag&gt;
        ///            &lt;Value type=&apos;Level&apos;&gt;1&lt;/Value&gt;
        ///        &lt;/Role&gt;
        ///        &lt;Role&gt;
        ///            &lt;Tag&gt;AssistantManager&lt;/Tag&gt;
        ///            &lt;Value type=&apos;Level&apos;&gt;2&lt;/Value&gt;
        ///        &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RoleHierarchy
        {
            get
            {
                return ResourceManager.GetString("RoleHierarchy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///    &lt;SafeOperations&gt;
        ///        &lt;Operation&gt;
        ///            ShopTransferIn
        ///        &lt;/Operation&gt;
        ///        &lt;Operation&gt;
        ///            ShopTransferOut
        ///        &lt;/Operation&gt;
        ///        &lt;Operation&gt;
        ///            BankTransferIn
        ///        &lt;/Operation&gt;
        ///        &lt;Operation&gt;
        ///            BankTransferOut
        ///        &lt;/Operation&gt;
        ///        &lt;Operation&gt;
        ///            BalanceSafe
        ///        &lt;/Operation&gt;
        ///        &lt;Operation&gt;
        ///            InternalSafeTransfer
        ///        &lt;/Operation&gt;        
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SafeOperations
        {
            get
            {
                return ResourceManager.GetString("SafeOperations", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap stopbutton
        {
            get
            {
                object obj = ResourceManager.GetObject("stopbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap stopbuttondepressed
        {
            get
            {
                object obj = ResourceManager.GetObject("stopbuttondepressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;variances&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt;var_max_amount&gt;999999.99&lt;/var_max_amount&gt;
        ///		&lt;var_min_amount&gt;100.00&lt;/var_min_amount&gt;
        ///		&lt;var_percent&gt;99.95000&lt;/var_percent&gt;
        ///	&lt;/variance_record&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt;var_max_amount&gt;999.99&lt;/var_max_amount&gt;
        ///		&lt;var_min_amount&gt;50.00&lt;/var_min_amount&gt;
        ///		&lt;var_percent&gt;49.95000&lt;/var_percent&gt;
        ///	&lt;/variance_record&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string variance
        {
            get
            {
                return ResourceManager.GetString("variance", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap vistabutton_blue
        {
            get
            {
                object obj = ResourceManager.GetObject("vistabutton_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
