//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.ProKnowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://casham.com/esb/adapters/proknow/wsdl", ConfigurationName="ProKnowService.proknowPort")]
    public interface proknowPort {
        
        // CODEGEN: Generating message contract since the operation GetAlternateManufacturers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/ProKnowAdapterService.serviceagent//GetAltern" +
            "ateManufacturers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.ProKnowService.GetAlternateManufacturersResponse GetAlternateManufacturers(Common.ProKnowService.GetAlternateManufacturersRequest request);
        
        // CODEGEN: Generating message contract since the operation GetModels is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/ProKnowAdapterService.serviceagent/proknowPor" +
            "tEndpoint1/GetModels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.ProKnowService.GetModelsResponse GetModels(Common.ProKnowService.GetModelsRequest request);
        
        // CODEGEN: Generating message contract since the operation GroupOfValues is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/ProKnowAdapterService.serviceagent//GroupOfVa" +
            "lues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.ProKnowService.GroupOfValuesResponse GroupOfValues(Common.ProKnowService.GroupOfValuesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetProknowDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/StarterProcesses/ProKnowAdapterService.serviceagent/proknowPor" +
            "tEndpoint1/GetProknowDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.ProKnowService.GetProknowDetailsResponse GetProknowDetails(Common.ProKnowService.GetProknowDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class alternateManufacturerRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private alternateManufacturerRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public alternateManufacturerRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class serviceInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainField;
        
        private endpointType sourceField;
        
        private string shopNumberField;
        
        private string terminalIDField;
        
        private string userIDField;
        
        private string transactionIDField;
        
        private System.DateTime timeStampField;
        
        private exceptionMessageType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public endpointType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string shopNumber {
            get {
                return this.shopNumberField;
            }
            set {
                this.shopNumberField = value;
                this.RaisePropertyChanged("shopNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string terminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("terminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public exceptionMessageType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class endpointType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string systemNameField;
        
        private string systemVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
                this.RaisePropertyChanged("systemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string systemVersion {
            get {
                return this.systemVersionField;
            }
            set {
                this.systemVersionField = value;
                this.RaisePropertyChanged("systemVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class proCallDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string newRetailField;
        
        private string lastUpdateDateField;
        
        private string yearIntroducedField;
        
        private string yearDiscontinuedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string newRetail {
            get {
                return this.newRetailField;
            }
            set {
                this.newRetailField = value;
                this.RaisePropertyChanged("newRetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
                this.RaisePropertyChanged("lastUpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string yearIntroduced {
            get {
                return this.yearIntroducedField;
            }
            set {
                this.yearIntroducedField = value;
                this.RaisePropertyChanged("yearIntroduced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string yearDiscontinued {
            get {
                return this.yearDiscontinuedField;
            }
            set {
                this.yearDiscontinuedField = value;
                this.RaisePropertyChanged("yearDiscontinued");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class valuesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double loanAmountField;
        
        private double purchaseAmountField;
        
        private double retailAmountField;
        
        private double loanVarLowField;
        
        private double loanVarHighField;
        
        private double purchaseVarLowField;
        
        private double purchaseVarHighField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double loanAmount {
            get {
                return this.loanAmountField;
            }
            set {
                this.loanAmountField = value;
                this.RaisePropertyChanged("loanAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double purchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("purchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double retailAmount {
            get {
                return this.retailAmountField;
            }
            set {
                this.retailAmountField = value;
                this.RaisePropertyChanged("retailAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double loanVarLow {
            get {
                return this.loanVarLowField;
            }
            set {
                this.loanVarLowField = value;
                this.RaisePropertyChanged("loanVarLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double loanVarHigh {
            get {
                return this.loanVarHighField;
            }
            set {
                this.loanVarHighField = value;
                this.RaisePropertyChanged("loanVarHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double purchaseVarLow {
            get {
                return this.purchaseVarLowField;
            }
            set {
                this.purchaseVarLowField = value;
                this.RaisePropertyChanged("purchaseVarLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double purchaseVarHigh {
            get {
                return this.purchaseVarHighField;
            }
            set {
                this.purchaseVarHighField = value;
                this.RaisePropertyChanged("purchaseVarHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class fixedFeatureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private int answerNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int answerNumber {
            get {
                return this.answerNumberField;
            }
            set {
                this.answerNumberField = value;
                this.RaisePropertyChanged("answerNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class fixedFeaturesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool printTagField;
        
        private fixedFeatureType[] featureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool printTag {
            get {
                return this.printTagField;
            }
            set {
                this.printTagField = value;
                this.RaisePropertyChanged("printTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature", Order=1)]
        public fixedFeatureType[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
                this.RaisePropertyChanged("feature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class preAnsweredType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mask1Field;
        
        private bool mask1FieldSpecified;
        
        private int mask2Field;
        
        private bool mask2FieldSpecified;
        
        private int mask3Field;
        
        private bool mask3FieldSpecified;
        
        private int mask4Field;
        
        private bool mask4FieldSpecified;
        
        private int mask5Field;
        
        private bool mask5FieldSpecified;
        
        private int mask6Field;
        
        private bool mask6FieldSpecified;
        
        private int mask7Field;
        
        private bool mask7FieldSpecified;
        
        private int mask8Field;
        
        private bool mask8FieldSpecified;
        
        private int mask9Field;
        
        private bool mask9FieldSpecified;
        
        private int mask10Field;
        
        private bool mask10FieldSpecified;
        
        private int mask11Field;
        
        private bool mask11FieldSpecified;
        
        private int mask12Field;
        
        private bool mask12FieldSpecified;
        
        private int mask13Field;
        
        private bool mask13FieldSpecified;
        
        private int mask14Field;
        
        private bool mask14FieldSpecified;
        
        private int mask15Field;
        
        private bool mask15FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int mask1 {
            get {
                return this.mask1Field;
            }
            set {
                this.mask1Field = value;
                this.RaisePropertyChanged("mask1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask1Specified {
            get {
                return this.mask1FieldSpecified;
            }
            set {
                this.mask1FieldSpecified = value;
                this.RaisePropertyChanged("mask1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int mask2 {
            get {
                return this.mask2Field;
            }
            set {
                this.mask2Field = value;
                this.RaisePropertyChanged("mask2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask2Specified {
            get {
                return this.mask2FieldSpecified;
            }
            set {
                this.mask2FieldSpecified = value;
                this.RaisePropertyChanged("mask2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int mask3 {
            get {
                return this.mask3Field;
            }
            set {
                this.mask3Field = value;
                this.RaisePropertyChanged("mask3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask3Specified {
            get {
                return this.mask3FieldSpecified;
            }
            set {
                this.mask3FieldSpecified = value;
                this.RaisePropertyChanged("mask3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int mask4 {
            get {
                return this.mask4Field;
            }
            set {
                this.mask4Field = value;
                this.RaisePropertyChanged("mask4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask4Specified {
            get {
                return this.mask4FieldSpecified;
            }
            set {
                this.mask4FieldSpecified = value;
                this.RaisePropertyChanged("mask4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int mask5 {
            get {
                return this.mask5Field;
            }
            set {
                this.mask5Field = value;
                this.RaisePropertyChanged("mask5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask5Specified {
            get {
                return this.mask5FieldSpecified;
            }
            set {
                this.mask5FieldSpecified = value;
                this.RaisePropertyChanged("mask5Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int mask6 {
            get {
                return this.mask6Field;
            }
            set {
                this.mask6Field = value;
                this.RaisePropertyChanged("mask6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask6Specified {
            get {
                return this.mask6FieldSpecified;
            }
            set {
                this.mask6FieldSpecified = value;
                this.RaisePropertyChanged("mask6Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int mask7 {
            get {
                return this.mask7Field;
            }
            set {
                this.mask7Field = value;
                this.RaisePropertyChanged("mask7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask7Specified {
            get {
                return this.mask7FieldSpecified;
            }
            set {
                this.mask7FieldSpecified = value;
                this.RaisePropertyChanged("mask7Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int mask8 {
            get {
                return this.mask8Field;
            }
            set {
                this.mask8Field = value;
                this.RaisePropertyChanged("mask8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask8Specified {
            get {
                return this.mask8FieldSpecified;
            }
            set {
                this.mask8FieldSpecified = value;
                this.RaisePropertyChanged("mask8Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int mask9 {
            get {
                return this.mask9Field;
            }
            set {
                this.mask9Field = value;
                this.RaisePropertyChanged("mask9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask9Specified {
            get {
                return this.mask9FieldSpecified;
            }
            set {
                this.mask9FieldSpecified = value;
                this.RaisePropertyChanged("mask9Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int mask10 {
            get {
                return this.mask10Field;
            }
            set {
                this.mask10Field = value;
                this.RaisePropertyChanged("mask10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask10Specified {
            get {
                return this.mask10FieldSpecified;
            }
            set {
                this.mask10FieldSpecified = value;
                this.RaisePropertyChanged("mask10Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int mask11 {
            get {
                return this.mask11Field;
            }
            set {
                this.mask11Field = value;
                this.RaisePropertyChanged("mask11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask11Specified {
            get {
                return this.mask11FieldSpecified;
            }
            set {
                this.mask11FieldSpecified = value;
                this.RaisePropertyChanged("mask11Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int mask12 {
            get {
                return this.mask12Field;
            }
            set {
                this.mask12Field = value;
                this.RaisePropertyChanged("mask12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask12Specified {
            get {
                return this.mask12FieldSpecified;
            }
            set {
                this.mask12FieldSpecified = value;
                this.RaisePropertyChanged("mask12Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int mask13 {
            get {
                return this.mask13Field;
            }
            set {
                this.mask13Field = value;
                this.RaisePropertyChanged("mask13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask13Specified {
            get {
                return this.mask13FieldSpecified;
            }
            set {
                this.mask13FieldSpecified = value;
                this.RaisePropertyChanged("mask13Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int mask14 {
            get {
                return this.mask14Field;
            }
            set {
                this.mask14Field = value;
                this.RaisePropertyChanged("mask14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask14Specified {
            get {
                return this.mask14FieldSpecified;
            }
            set {
                this.mask14FieldSpecified = value;
                this.RaisePropertyChanged("mask14Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int mask15 {
            get {
                return this.mask15Field;
            }
            set {
                this.mask15Field = value;
                this.RaisePropertyChanged("mask15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mask15Specified {
            get {
                return this.mask15FieldSpecified;
            }
            set {
                this.mask15FieldSpecified = value;
                this.RaisePropertyChanged("mask15Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class combinationCategoryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int secondaryManufacturerField;
        
        private int secondaryModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int secondaryManufacturer {
            get {
                return this.secondaryManufacturerField;
            }
            set {
                this.secondaryManufacturerField = value;
                this.RaisePropertyChanged("secondaryManufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int secondaryModel {
            get {
                return this.secondaryModelField;
            }
            set {
                this.secondaryModelField = value;
                this.RaisePropertyChanged("secondaryModel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModelMatchType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoryCodeField;
        
        private combinationCategoryType combinationCategoryInfoField;
        
        private preAnsweredType preAnsweredField;
        
        private fixedFeaturesType fixedFeaturesField;
        
        private valuesType values1Field;
        
        private valuesType values2Field;
        
        private valuesType values3Field;
        
        private valuesType values4Field;
        
        private proCallDataType proCallDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public combinationCategoryType combinationCategoryInfo {
            get {
                return this.combinationCategoryInfoField;
            }
            set {
                this.combinationCategoryInfoField = value;
                this.RaisePropertyChanged("combinationCategoryInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public preAnsweredType preAnswered {
            get {
                return this.preAnsweredField;
            }
            set {
                this.preAnsweredField = value;
                this.RaisePropertyChanged("preAnswered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public fixedFeaturesType fixedFeatures {
            get {
                return this.fixedFeaturesField;
            }
            set {
                this.fixedFeaturesField = value;
                this.RaisePropertyChanged("fixedFeatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public valuesType values1 {
            get {
                return this.values1Field;
            }
            set {
                this.values1Field = value;
                this.RaisePropertyChanged("values1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public valuesType values2 {
            get {
                return this.values2Field;
            }
            set {
                this.values2Field = value;
                this.RaisePropertyChanged("values2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public valuesType values3 {
            get {
                return this.values3Field;
            }
            set {
                this.values3Field = value;
                this.RaisePropertyChanged("values3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public valuesType values4 {
            get {
                return this.values4Field;
            }
            set {
                this.values4Field = value;
                this.RaisePropertyChanged("values4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public proCallDataType proCallData {
            get {
                return this.proCallDataField;
            }
            set {
                this.proCallDataField = value;
                this.RaisePropertyChanged("proCallData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModelReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private manModelReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public manModelReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModelReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("manModelMatch", typeof(manModelMatchType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/cim/common/common_business_objects")]
    public partial class businessExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string descriptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModelRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private manModelRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public manModelRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModelRequestTypeServiceData : serviceDataRequestType {
        
        private string manufacturerField;
        
        private string modelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesOutputType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseKeyField;
        
        private double pKR1Field;
        
        private bool pKR1FieldSpecified;
        
        private double pKR2Field;
        
        private bool pKR2FieldSpecified;
        
        private double pKR3Field;
        
        private bool pKR3FieldSpecified;
        
        private double pKR4Field;
        
        private bool pKR4FieldSpecified;
        
        private string todaysNewRetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseKey {
            get {
                return this.responseKeyField;
            }
            set {
                this.responseKeyField = value;
                this.RaisePropertyChanged("responseKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PKR1 {
            get {
                return this.pKR1Field;
            }
            set {
                this.pKR1Field = value;
                this.RaisePropertyChanged("PKR1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKR1Specified {
            get {
                return this.pKR1FieldSpecified;
            }
            set {
                this.pKR1FieldSpecified = value;
                this.RaisePropertyChanged("PKR1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double PKR2 {
            get {
                return this.pKR2Field;
            }
            set {
                this.pKR2Field = value;
                this.RaisePropertyChanged("PKR2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKR2Specified {
            get {
                return this.pKR2FieldSpecified;
            }
            set {
                this.pKR2FieldSpecified = value;
                this.RaisePropertyChanged("PKR2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double PKR3 {
            get {
                return this.pKR3Field;
            }
            set {
                this.pKR3Field = value;
                this.RaisePropertyChanged("PKR3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKR3Specified {
            get {
                return this.pKR3FieldSpecified;
            }
            set {
                this.pKR3FieldSpecified = value;
                this.RaisePropertyChanged("PKR3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double PKR4 {
            get {
                return this.pKR4Field;
            }
            set {
                this.pKR4Field = value;
                this.RaisePropertyChanged("PKR4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKR4Specified {
            get {
                return this.pKR4FieldSpecified;
            }
            set {
                this.pKR4FieldSpecified = value;
                this.RaisePropertyChanged("PKR4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string todaysNewRetail {
            get {
                return this.todaysNewRetailField;
            }
            set {
                this.todaysNewRetailField = value;
                this.RaisePropertyChanged("todaysNewRetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private groupOfValuesTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public groupOfValuesTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupOfValuesOutput", typeof(groupOfValuesOutputType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesInputType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseKeyField;
        
        private int categoryCodeField;
        
        private string manufacturerField;
        
        private string modelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseKey {
            get {
                return this.responseKeyField;
            }
            set {
                this.responseKeyField = value;
                this.RaisePropertyChanged("responseKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("Model");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private groupOfValuesRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public groupOfValuesRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class groupOfValuesRequestTypeServiceData : serviceDataRequestType {
        
        private groupOfValuesInputType[] groupOfValuesInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupOfValuesInput", Order=0)]
        public groupOfValuesInputType[] groupOfValuesInput {
            get {
                return this.groupOfValuesInputField;
            }
            set {
                this.groupOfValuesInputField = value;
                this.RaisePropertyChanged("groupOfValuesInput");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class getModelsReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private getModelsReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public getModelsReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class getModelsReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("model", typeof(manModType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class manModType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private int answerNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int answerNumber {
            get {
                return this.answerNumberField;
            }
            set {
                this.answerNumberField = value;
                this.RaisePropertyChanged("answerNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class getModelsRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private getModelsRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public getModelsRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class getModelsRequestTypeServiceData : serviceDataRequestType {
        
        private string manufacturerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class alternameManufacturerReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private alternameManufacturerReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public alternameManufacturerReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class alternameManufacturerReplyTypeServiceData : serviceDataReplyType {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("alternateManufacturer", typeof(manModType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class userDefinedElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class exceptionMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionCodeField;
        
        private string sourceMessageField;
        
        private string subjectField;
        
        private System.DateTime dateTimestampField;
        
        private bool dateTimestampFieldSpecified;
        
        private string noteField;
        
        private endpointType originationField;
        
        private endpointType commonField;
        
        private endpointType destinationField;
        
        private string convertionIdField;
        
        private userDefinedElementType[] userDefinedElementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string exceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("exceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceMessage {
            get {
                return this.sourceMessageField;
            }
            set {
                this.sourceMessageField = value;
                this.RaisePropertyChanged("sourceMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime dateTimestamp {
            get {
                return this.dateTimestampField;
            }
            set {
                this.dateTimestampField = value;
                this.RaisePropertyChanged("dateTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimestampSpecified {
            get {
                return this.dateTimestampFieldSpecified;
            }
            set {
                this.dateTimestampFieldSpecified = value;
                this.RaisePropertyChanged("dateTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public endpointType origination {
            get {
                return this.originationField;
            }
            set {
                this.originationField = value;
                this.RaisePropertyChanged("origination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public endpointType common {
            get {
                return this.commonField;
            }
            set {
                this.commonField = value;
                this.RaisePropertyChanged("common");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public endpointType destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string convertionId {
            get {
                return this.convertionIdField;
            }
            set {
                this.convertionIdField = value;
                this.RaisePropertyChanged("convertionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userDefinedElements", Order=9)]
        public userDefinedElementType[] userDefinedElements {
            get {
                return this.userDefinedElementsField;
            }
            set {
                this.userDefinedElementsField = value;
                this.RaisePropertyChanged("userDefinedElements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/adapters/proknow")]
    public partial class alternateManufacturerRequestTypeServiceData : serviceDataRequestType {
        
        private string manufacturerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlternateManufacturersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.alternateManufacturerRequestType alternateManufacturerRequest;
        
        public GetAlternateManufacturersRequest() {
        }
        
        public GetAlternateManufacturersRequest(Common.ProKnowService.alternateManufacturerRequestType alternateManufacturerRequest) {
            this.alternateManufacturerRequest = alternateManufacturerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlternateManufacturersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.alternameManufacturerReplyType alternameManufacturerReply;
        
        public GetAlternateManufacturersResponse() {
        }
        
        public GetAlternateManufacturersResponse(Common.ProKnowService.alternameManufacturerReplyType alternameManufacturerReply) {
            this.alternameManufacturerReply = alternameManufacturerReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getModelsRequest", Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.getModelsRequestType getModelsRequest1;
        
        public GetModelsRequest() {
        }
        
        public GetModelsRequest(Common.ProKnowService.getModelsRequestType getModelsRequest1) {
            this.getModelsRequest1 = getModelsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.getModelsReplyType getModelsReply;
        
        public GetModelsResponse() {
        }
        
        public GetModelsResponse(Common.ProKnowService.getModelsReplyType getModelsReply) {
            this.getModelsReply = getModelsReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupOfValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="groupOfValuesRequest", Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.groupOfValuesRequestType groupOfValuesRequest1;
        
        public GroupOfValuesRequest() {
        }
        
        public GroupOfValuesRequest(Common.ProKnowService.groupOfValuesRequestType groupOfValuesRequest1) {
            this.groupOfValuesRequest1 = groupOfValuesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupOfValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.groupOfValuesType groupOfValuesReply;
        
        public GroupOfValuesResponse() {
        }
        
        public GroupOfValuesResponse(Common.ProKnowService.groupOfValuesType groupOfValuesReply) {
            this.groupOfValuesReply = groupOfValuesReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProknowDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.manModelRequestType manModelRequest;
        
        public GetProknowDetailsRequest() {
        }
        
        public GetProknowDetailsRequest(Common.ProKnowService.manModelRequestType manModelRequest) {
            this.manModelRequest = manModelRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProknowDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/adapters/proknow", Order=0)]
        public Common.ProKnowService.manModelReplyType manModelReply;
        
        public GetProknowDetailsResponse() {
        }
        
        public GetProknowDetailsResponse(Common.ProKnowService.manModelReplyType manModelReply) {
            this.manModelReply = manModelReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface proknowPortChannel : Common.ProKnowService.proknowPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class proknowPortClient : System.ServiceModel.ClientBase<Common.ProKnowService.proknowPort>, Common.ProKnowService.proknowPort {
        
        public proknowPortClient() {
        }
        
        public proknowPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public proknowPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proknowPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proknowPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ProKnowService.GetAlternateManufacturersResponse Common.ProKnowService.proknowPort.GetAlternateManufacturers(Common.ProKnowService.GetAlternateManufacturersRequest request) {
            return base.Channel.GetAlternateManufacturers(request);
        }
        
        public Common.ProKnowService.alternameManufacturerReplyType GetAlternateManufacturers(Common.ProKnowService.alternateManufacturerRequestType alternateManufacturerRequest) {
            Common.ProKnowService.GetAlternateManufacturersRequest inValue = new Common.ProKnowService.GetAlternateManufacturersRequest();
            inValue.alternateManufacturerRequest = alternateManufacturerRequest;
            Common.ProKnowService.GetAlternateManufacturersResponse retVal = ((Common.ProKnowService.proknowPort)(this)).GetAlternateManufacturers(inValue);
            return retVal.alternameManufacturerReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ProKnowService.GetModelsResponse Common.ProKnowService.proknowPort.GetModels(Common.ProKnowService.GetModelsRequest request) {
            return base.Channel.GetModels(request);
        }
        
        public Common.ProKnowService.getModelsReplyType GetModels(Common.ProKnowService.getModelsRequestType getModelsRequest1) {
            Common.ProKnowService.GetModelsRequest inValue = new Common.ProKnowService.GetModelsRequest();
            inValue.getModelsRequest1 = getModelsRequest1;
            Common.ProKnowService.GetModelsResponse retVal = ((Common.ProKnowService.proknowPort)(this)).GetModels(inValue);
            return retVal.getModelsReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ProKnowService.GroupOfValuesResponse Common.ProKnowService.proknowPort.GroupOfValues(Common.ProKnowService.GroupOfValuesRequest request) {
            return base.Channel.GroupOfValues(request);
        }
        
        public Common.ProKnowService.groupOfValuesType GroupOfValues(Common.ProKnowService.groupOfValuesRequestType groupOfValuesRequest1) {
            Common.ProKnowService.GroupOfValuesRequest inValue = new Common.ProKnowService.GroupOfValuesRequest();
            inValue.groupOfValuesRequest1 = groupOfValuesRequest1;
            Common.ProKnowService.GroupOfValuesResponse retVal = ((Common.ProKnowService.proknowPort)(this)).GroupOfValues(inValue);
            return retVal.groupOfValuesReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ProKnowService.GetProknowDetailsResponse Common.ProKnowService.proknowPort.GetProknowDetails(Common.ProKnowService.GetProknowDetailsRequest request) {
            return base.Channel.GetProknowDetails(request);
        }
        
        public Common.ProKnowService.manModelReplyType GetProknowDetails(Common.ProKnowService.manModelRequestType manModelRequest) {
            Common.ProKnowService.GetProknowDetailsRequest inValue = new Common.ProKnowService.GetProknowDetailsRequest();
            inValue.manModelRequest = manModelRequest;
            Common.ProKnowService.GetProknowDetailsResponse retVal = ((Common.ProKnowService.proknowPort)(this)).GetProknowDetails(inValue);
            return retVal.manModelReply;
        }
    }
}
