//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawnUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PawnUtilities.RoleResources", typeof(RoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashTransfer.
        /// </summary>
        internal static string CASHTRANSFER {
            get {
                return ResourceManager.GetString("CASHTRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChargeOff.
        /// </summary>
        internal static string CHARGEOFF {
            get {
                return ResourceManager.GetString("CHARGEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePFIListPanel.
        /// </summary>
        internal static string CREATEPFILISTPANEL {
            get {
                return ResourceManager.GetString("CREATEPFILISTPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerHold.
        /// </summary>
        internal static string CUSTOMERHOLD {
            get {
                return ResourceManager.GetString("CUSTOMERHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Entry.
        /// </summary>
        internal static string MANUALENTRY {
            get {
                return ResourceManager.GetString("MANUALENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPawnLoan.
        /// </summary>
        internal static string NEWPAWNLOAN {
            get {
                return ResourceManager.GetString("NEWPAWNLOAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Loan Inquiry All Locations.
        /// </summary>
        internal static string PAWNLOANINQUIRYALLLOCATIONS {
            get {
                return ResourceManager.GetString("PAWNLOANINQUIRYALLLOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Loan Inquiry Multiple Locations current Market.
        /// </summary>
        internal static string PAWNLOANINQUIRYCURRENTMARKET {
            get {
                return ResourceManager.GetString("PAWNLOANINQUIRYCURRENTMARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Loan Inquiry Current Location.
        /// </summary>
        internal static string PAWNLOANINQUIRYCURRLOC {
            get {
                return ResourceManager.GetString("PAWNLOANINQUIRYCURRLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Loan Inquiry Multiple Locations current Region.
        /// </summary>
        internal static string PAWNLOIANINQUIRYCURRENTREGION {
            get {
                return ResourceManager.GetString("PAWNLOIANINQUIRYCURRENTREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFIVerifyPanel.
        /// </summary>
        internal static string PFIVERIFYPANEL {
            get {
                return ResourceManager.GetString("PFIVERIFYPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoliceActivitiesAll.
        /// </summary>
        internal static string POLICEACTIVITIESALL {
            get {
                return ResourceManager.GetString("POLICEACTIVITIESALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Restitution Only.
        /// </summary>
        internal static string POLICERESTITUTIONONLY {
            get {
                return ResourceManager.GetString("POLICERESTITUTIONONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostPFIActivityPanel.
        /// </summary>
        internal static string POSTPFIACTIVITYPANEL {
            get {
                return ResourceManager.GetString("POSTPFIACTIVITYPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Gun Book In Any Location.
        /// </summary>
        internal static string PRINTGUNBOOKINANYLOCATION {
            get {
                return ResourceManager.GetString("PRINTGUNBOOKINANYLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Gun Book In Current Location.
        /// </summary>
        internal static string PRINTGUNBOOKINCURRENTLOCATION {
            get {
                return ResourceManager.GetString("PRINTGUNBOOKINCURRENTLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintPFIMailer.
        /// </summary>
        internal static string PRINTPFIMAILER {
            get {
                return ResourceManager.GetString("PRINTPFIMAILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Security Barcode.
        /// </summary>
        internal static string PRINTSECURITYBARCODE {
            get {
                return ResourceManager.GetString("PRINTSECURITYBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redescribe Merchandise.
        /// </summary>
        internal static string REDESCRIBEMERCHANDISE {
            get {
                return ResourceManager.GetString("REDESCRIBEMERCHANDISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReprintTags.
        /// </summary>
        internal static string REPRINTTAGS {
            get {
                return ResourceManager.GetString("REPRINTTAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string SERVICES {
            get {
                return ResourceManager.GetString("SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferOut.
        /// </summary>
        internal static string TRANSFEROUT {
            get {
                return ResourceManager.GetString("TRANSFEROUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View PhysicalDescriptionTab.
        /// </summary>
        internal static string VIEWPHYSICALDESCRIPTIONTAB {
            get {
                return ResourceManager.GetString("VIEWPHYSICALDESCRIPTIONTAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewReferenceNumber.
        /// </summary>
        internal static string VIEWREFERENCENUMBER {
            get {
                return ResourceManager.GetString("VIEWREFERENCENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Transactions and Services.
        /// </summary>
        internal static string VOIDSERVICES {
            get {
                return ResourceManager.GetString("VOIDSERVICES", resourceCulture);
            }
        }
    }
}
