//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.AddressService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://casham.com/esb/common/services/address/wsdl", ConfigurationName="AddressService.addressServicePort")]
    public interface addressServicePort {
        
        // CODEGEN: Generating message contract since the operation lookupCityState is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/Address/StarterProcesses/Address_Service.serviceagent/addressS" +
            "erviceHTTPPortEndpoint/lookupCityState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.AddressService.lookupCityStateResponse lookupCityState(Common.AddressService.lookupCityStateRequest request);
        
        // CODEGEN: Generating message contract since the operation validateAddress is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessProcesses/Address/StarterProcesses/Address_Service.serviceagent/addressS" +
            "erviceHTTPPortEndpoint/validateAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataReplyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataRequestType))]
        Common.AddressService.validateAddressResponse validateAddress(Common.AddressService.validateAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/address")]
    public partial class cityStateLookupRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private cityStateLookupRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public cityStateLookupRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class serviceInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainField;
        
        private endpointType sourceField;
        
        private string shopNumberField;
        
        private string terminalIDField;
        
        private string userIDField;
        
        private string transactionIDField;
        
        private System.DateTime timeStampField;
        
        private exceptionMessageType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public endpointType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string shopNumber {
            get {
                return this.shopNumberField;
            }
            set {
                this.shopNumberField = value;
                this.RaisePropertyChanged("shopNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string terminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("terminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public exceptionMessageType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class endpointType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string systemNameField;
        
        private string systemVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
                this.RaisePropertyChanged("systemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string systemVersion {
            get {
                return this.systemVersionField;
            }
            set {
                this.systemVersionField = value;
                this.RaisePropertyChanged("systemVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/address")]
    public partial class addressValidationReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private addressValidationReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public addressValidationReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/common/services/address")]
    public partial class addressValidationReplyTypeServiceData : serviceDataReplyType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address", typeof(addressType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/cim/common/common_business_objects")]
    public partial class addressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private addressTypeType typeField;
        
        private string[] streetField;
        
        private string unitField;
        
        private string cityField;
        
        private string stateField;
        
        private postalCodeType postalCodeField;
        
        private string countryField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public addressTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("street", Order=1)]
        public string[] street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public postalCodeType postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/cim/common/common_business_objects")]
    public enum addressTypeType {
        
        /// <remarks/>
        PHYSICAL,
        
        /// <remarks/>
        MAIL,
        
        /// <remarks/>
        WORK,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/cim/common/common_business_objects")]
    public partial class postalCodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipCodeField;
        
        private string zipPlusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string zipPlus {
            get {
                return this.zipPlusField;
            }
            set {
                this.zipPlusField = value;
                this.RaisePropertyChanged("zipPlus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/cim/common/common_business_objects")]
    public partial class businessExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string descriptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/address")]
    public partial class addressValidationRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private addressValidationRequestTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public addressValidationRequestTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/common/services/address")]
    public partial class addressValidationRequestTypeServiceData : serviceDataRequestType {
        
        private addressType addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public abstract partial class serviceDataRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/address")]
    public partial class cityStateLookupReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInformationType serviceInformationField;
        
        private cityStateLookupReplyTypeServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks", Order=0)]
        public serviceInformationType serviceInformation {
            get {
                return this.serviceInformationField;
            }
            set {
                this.serviceInformationField = value;
                this.RaisePropertyChanged("serviceInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public cityStateLookupReplyTypeServiceData serviceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
                this.RaisePropertyChanged("serviceData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/common/services/address")]
    public partial class cityStateLookupReplyTypeServiceData : serviceDataReplyType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address", typeof(addressType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("businessException", typeof(businessExceptionType), Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class userDefinedElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://casham.com/esb/common/services/standard_message_blocks")]
    public partial class exceptionMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionCodeField;
        
        private string sourceMessageField;
        
        private string subjectField;
        
        private System.DateTime dateTimestampField;
        
        private bool dateTimestampFieldSpecified;
        
        private string noteField;
        
        private endpointType originationField;
        
        private endpointType commonField;
        
        private endpointType destinationField;
        
        private string convertionIdField;
        
        private userDefinedElementType[] userDefinedElementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string exceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("exceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceMessage {
            get {
                return this.sourceMessageField;
            }
            set {
                this.sourceMessageField = value;
                this.RaisePropertyChanged("sourceMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime dateTimestamp {
            get {
                return this.dateTimestampField;
            }
            set {
                this.dateTimestampField = value;
                this.RaisePropertyChanged("dateTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimestampSpecified {
            get {
                return this.dateTimestampFieldSpecified;
            }
            set {
                this.dateTimestampFieldSpecified = value;
                this.RaisePropertyChanged("dateTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public endpointType origination {
            get {
                return this.originationField;
            }
            set {
                this.originationField = value;
                this.RaisePropertyChanged("origination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public endpointType common {
            get {
                return this.commonField;
            }
            set {
                this.commonField = value;
                this.RaisePropertyChanged("common");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public endpointType destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string convertionId {
            get {
                return this.convertionIdField;
            }
            set {
                this.convertionIdField = value;
                this.RaisePropertyChanged("convertionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userDefinedElements", Order=9)]
        public userDefinedElementType[] userDefinedElements {
            get {
                return this.userDefinedElementsField;
            }
            set {
                this.userDefinedElementsField = value;
                this.RaisePropertyChanged("userDefinedElements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://casham.com/esb/common/services/address")]
    public partial class cityStateLookupRequestTypeServiceData : serviceDataRequestType {
        
        private postalCodeType postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://casham.com/cim/common/common_business_objects", Order=0)]
        public postalCodeType postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lookupCityStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/common/services/address", Order=0)]
        public Common.AddressService.cityStateLookupRequestType cityStateLookupRequest;
        
        public lookupCityStateRequest() {
        }
        
        public lookupCityStateRequest(Common.AddressService.cityStateLookupRequestType cityStateLookupRequest) {
            this.cityStateLookupRequest = cityStateLookupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lookupCityStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/common/services/address", Order=0)]
        public Common.AddressService.cityStateLookupReplyType cityStateLookupReply;
        
        public lookupCityStateResponse() {
        }
        
        public lookupCityStateResponse(Common.AddressService.cityStateLookupReplyType cityStateLookupReply) {
            this.cityStateLookupReply = cityStateLookupReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/common/services/address", Order=0)]
        public Common.AddressService.addressValidationRequestType addressValidationRequest;
        
        public validateAddressRequest() {
        }
        
        public validateAddressRequest(Common.AddressService.addressValidationRequestType addressValidationRequest) {
            this.addressValidationRequest = addressValidationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://casham.com/esb/common/services/address", Order=0)]
        public Common.AddressService.addressValidationReplyType addressValidationReply;
        
        public validateAddressResponse() {
        }
        
        public validateAddressResponse(Common.AddressService.addressValidationReplyType addressValidationReply) {
            this.addressValidationReply = addressValidationReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addressServicePortChannel : Common.AddressService.addressServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addressServicePortClient : System.ServiceModel.ClientBase<Common.AddressService.addressServicePort>, Common.AddressService.addressServicePort {
        
        public addressServicePortClient() {
        }
        
        public addressServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addressServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addressServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addressServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.AddressService.lookupCityStateResponse Common.AddressService.addressServicePort.lookupCityState(Common.AddressService.lookupCityStateRequest request) {
            return base.Channel.lookupCityState(request);
        }
        
        public Common.AddressService.cityStateLookupReplyType lookupCityState(Common.AddressService.cityStateLookupRequestType cityStateLookupRequest) {
            var inValue = new Common.AddressService.lookupCityStateRequest();
            inValue.cityStateLookupRequest = cityStateLookupRequest;
            Common.AddressService.lookupCityStateResponse retVal = ((Common.AddressService.addressServicePort)(this)).lookupCityState(inValue);
            return retVal.cityStateLookupReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.AddressService.validateAddressResponse Common.AddressService.addressServicePort.validateAddress(Common.AddressService.validateAddressRequest request) {
            return base.Channel.validateAddress(request);
        }
        
        public Common.AddressService.addressValidationReplyType validateAddress(Common.AddressService.addressValidationRequestType addressValidationRequest) {
            var inValue = new Common.AddressService.validateAddressRequest();
            inValue.addressValidationRequest = addressValidationRequest;
            Common.AddressService.validateAddressResponse retVal = ((Common.AddressService.addressServicePort)(this)).validateAddress(inValue);
            return retVal.addressValidationReply;
        }
    }
}
