//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashlinxDesktopLoadTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashlinxDesktopLoadTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ns0:categoryList xmlns:ns0=&quot;http://casham.com/esb/adapters/proknow&quot;&gt;
        ///    &lt;ns0:childCat&gt;
        ///        &lt;ns0:catCode&gt;1000&lt;/ns0:catCode&gt;
        ///        &lt;ns0:catCode1&gt;1&lt;/ns0:catCode1&gt;
        ///        &lt;ns0:catCode2&gt;0&lt;/ns0:catCode2&gt;
        ///        &lt;ns0:catCode3&gt;0&lt;/ns0:catCode3&gt;
        ///        &lt;ns0:catCode4&gt;0&lt;/ns0:catCode4&gt;
        ///        &lt;ns0:catMaskPointer&gt;1000&lt;/ns0:catMaskPointer&gt;
        ///        &lt;ns0:catComplete&gt;N&lt;/ns0:catComplete&gt;
        ///        &lt;ns0:catAllowed&gt;Y&lt;/ns0:catAllowed&gt;
        ///        &lt;ns0:catDescription&gt;JEWELRY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;variances&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt;var_max_amount&gt;999999.99&lt;/var_max_amount&gt;
        ///		&lt;var_min_amount&gt;100.00&lt;/var_min_amount&gt;
        ///		&lt;var_percent&gt;99.95000&lt;/var_percent&gt;
        ///	&lt;/variance_record&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt;var_max_amount&gt;999.99&lt;/var_max_amount&gt;
        ///		&lt;var_min_amount&gt;50.00&lt;/var_min_amount&gt;
        ///		&lt;var_percent&gt;49.95000&lt;/var_percent&gt;
        ///	&lt;/variance_record&gt;
        ///	&lt;variance_record&gt;
        ///		&lt;var_doc_type&gt;R&lt;/var_doc_type&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string variance {
            get {
                return ResourceManager.GetString("variance", resourceCulture);
            }
        }
    }
}
