//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditQueries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuditQueries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string ExceptionBoxEnabled {
            get {
                return ResourceManager.GetString("ExceptionBoxEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string IgnoreQueries {
            get {
                return ResourceManager.GetString("IgnoreQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string NumberQueries {
            get {
                return ResourceManager.GetString("NumberQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99535a447a5ab36823bd6150acc267f9.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a jewelry item that has an inactive refurb tag on it with no ICN..
        /// </summary>
        internal static string Query_1_Desc {
            get {
                return ResourceManager.GetString("Query_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindJewelryItemWithInactiveRefurbAndNoIcn.
        /// </summary>
        internal static string Query_1_Name {
            get {
                return ResourceManager.GetString("Query_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query1Params.
        /// </summary>
        internal static string Query_1_Params {
            get {
                return ResourceManager.GetString("Query_1_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query1SQL.
        /// </summary>
        internal static string Query_1_SQL {
            get {
                return ResourceManager.GetString("Query_1_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an ICN based on the refurb number..
        /// </summary>
        internal static string Query_2_Desc {
            get {
                return ResourceManager.GetString("Query_2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindIcnBasedOnRefurbNumber.
        /// </summary>
        internal static string Query_2_Name {
            get {
                return ResourceManager.GetString("Query_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p_rfb_no:number,p_store_number:string.
        /// </summary>
        internal static string Query_2_Params {
            get {
                return ResourceManager.GetString("Query_2_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  icn_store, icn_year, icn_doc, icn_doc_type, icn_item, icn_sub_item, status_cd, md_desc from mdse where rfb_no = ?p_rfb_no? and storenumber = ?p_store_number?.
        /// </summary>
        internal static string Query_2_SQL {
            get {
                return ResourceManager.GetString("Query_2_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find active general inventory by manufacturer, model, and serial number..
        /// </summary>
        internal static string Query_3_Desc {
            get {
                return ResourceManager.GetString("Query_3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindGeneralInventoryByMfgrModelSerialNumber.
        /// </summary>
        internal static string Query_3_Name {
            get {
                return ResourceManager.GetString("Query_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p_manufacturer:string,p_model_nr:string,p_serial_nr:string,p_store_number:string.
        /// </summary>
        internal static string Query_3_Params {
            get {
                return ResourceManager.GetString("Query_3_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select icn_store, icn_year, icn_doc, icn_doc_type, icn_item, icn_sub_item, status_cd, md_desc from mdse where storenumber = ?p_store_number? and (?p_manufacturer? is null or manufacturer = upper(?p_manufacturer?)) and (?p_model_nr? is null or model = upper(?p_model_nr?)) and (?p_serial_nr? is null or serial_number = upper(?p_serial_nr?)).
        /// </summary>
        internal static string Query_3_SQL {
            get {
                return ResourceManager.GetString("Query_3_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find active jewelry inventory by category, karat, and weight..
        /// </summary>
        internal static string Query_4_Desc {
            get {
                return ResourceManager.GetString("Query_4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindJewelryInventoryByCategoryKaratWeight.
        /// </summary>
        internal static string Query_4_Name {
            get {
                return ResourceManager.GetString("Query_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p_cat_code:number,p_weight:string,p_karat:string,p_store_number:string.
        /// </summary>
        internal static string Query_4_Params {
            get {
                return ResourceManager.GetString("Query_4_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select /*+ INDEX(mdse,mdse(md_desc)) */ icn_store, icn_year, icn_doc, icn_doc_type, icn_item, icn_sub_item, status_cd, md_desc from mdse where storenumber = ?p_store_number? and cat_code between 1000 and 1999 and (?p_cat_code? is null or cat_code = ?p_cat_code?) and (?p_weight? is null or md_desc like &apos;%&apos; || ?p_weight? || &apos;% GRM%&apos;) and (?p_karat? is null or md_desc like &apos;%&apos; || ?p_karat? || &apos;% KT%&apos;).
        /// </summary>
        internal static string Query_4_SQL {
            get {
                return ResourceManager.GetString("Query_4_SQL", resourceCulture);
            }
        }
    }
}
