//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuButtonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuButtonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Support.MenuButtonResources", typeof(MenuButtonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap achadmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("achadmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap achadmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("achadmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap achadmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("achadmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap achadmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("achadmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjbarcodeform_button_depressed {
            get {
                object obj = ResourceManager.GetObject("adjbarcodeform_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjbarcodeform_button_disabled {
            get {
                object obj = ResourceManager.GetObject("adjbarcodeform_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjbarcodeform_button_hover {
            get {
                object obj = ResourceManager.GetObject("adjbarcodeform_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjbarcodeform_button_normal {
            get {
                object obj = ResourceManager.GetObject("adjbarcodeform_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjburncodes_button_depressed {
            get {
                object obj = ResourceManager.GetObject("adjburncodes_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjburncodes_button_disabled {
            get {
                object obj = ResourceManager.GetObject("adjburncodes_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjburncodes_button_hover {
            get {
                object obj = ResourceManager.GetObject("adjburncodes_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adjburncodes_button_normal {
            get {
                object obj = ResourceManager.GetObject("adjburncodes_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap artivaadmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("artivaadmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap artivaadmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("artivaadmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap artivaadmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("artivaadmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap artivaadmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("artivaadmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_button_depressed {
            get {
                object obj = ResourceManager.GetObject("back_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_button_disabled {
            get {
                object obj = ResourceManager.GetObject("back_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_button_hover {
            get {
                object obj = ResourceManager.GetObject("back_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_button_normal {
            get {
                object obj = ResourceManager.GetObject("back_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcodeform_button_depressed {
            get {
                object obj = ResourceManager.GetObject("barcodeform_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcodeform_button_disabled {
            get {
                object obj = ResourceManager.GetObject("barcodeform_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcodeform_button_hover {
            get {
                object obj = ResourceManager.GetObject("barcodeform_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcodeform_button_normal {
            get {
                object obj = ResourceManager.GetObject("barcodeform_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busruleparams_button_depressed {
            get {
                object obj = ResourceManager.GetObject("busruleparams_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busruleparams_button_disabled {
            get {
                object obj = ResourceManager.GetObject("busruleparams_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busruleparams_button_hover {
            get {
                object obj = ResourceManager.GetObject("busruleparams_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busruleparams_button_normal {
            get {
                object obj = ResourceManager.GetObject("busruleparams_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cashtubes_button_depressed {
            get {
                object obj = ResourceManager.GetObject("cashtubes_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cashtubes_button_disabled {
            get {
                object obj = ResourceManager.GetObject("cashtubes_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cashtubes_button_hover {
            get {
                object obj = ResourceManager.GetObject("cashtubes_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cashtubes_button_normal {
            get {
                object obj = ResourceManager.GetObject("cashtubes_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap changepassword_button_depressed {
            get {
                object obj = ResourceManager.GetObject("changepassword_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap changepassword_button_disabled {
            get {
                object obj = ResourceManager.GetObject("changepassword_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap changepassword_button_hover {
            get {
                object obj = ResourceManager.GetObject("changepassword_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap changepassword_button_normal {
            get {
                object obj = ResourceManager.GetObject("changepassword_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cleartemp_button_depressed {
            get {
                object obj = ResourceManager.GetObject("cleartemp_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cleartemp_button_disabled {
            get {
                object obj = ResourceManager.GetObject("cleartemp_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cleartemp_button_hover {
            get {
                object obj = ResourceManager.GetObject("cleartemp_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cleartemp_button_normal {
            get {
                object obj = ResourceManager.GetObject("cleartemp_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clxadmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("clxadmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clxadmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("clxadmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clxadmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("clxadmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clxadmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("clxadmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuration_button_depressed {
            get {
                object obj = ResourceManager.GetObject("configuration_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuration_button_disabled {
            get {
                object obj = ResourceManager.GetObject("configuration_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuration_button_hover {
            get {
                object obj = ResourceManager.GetObject("configuration_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuration_button_normal {
            get {
                object obj = ResourceManager.GetObject("configuration_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap createdload_button_depressed {
            get {
                object obj = ResourceManager.GetObject("createdload_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap createdload_button_disabled {
            get {
                object obj = ResourceManager.GetObject("createdload_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap createdload_button_hover {
            get {
                object obj = ResourceManager.GetObject("createdload_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap createdload_button_normal {
            get {
                object obj = ResourceManager.GetObject("createdload_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custmaint_button_depressed {
            get {
                object obj = ResourceManager.GetObject("custmaint_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custmaint_button_disabled {
            get {
                object obj = ResourceManager.GetObject("custmaint_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custmaint_button_hover {
            get {
                object obj = ResourceManager.GetObject("custmaint_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custmaint_button_normal {
            get {
                object obj = ResourceManager.GetObject("custmaint_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customerservice_button_depressed {
            get {
                object obj = ResourceManager.GetObject("customerservice_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customerservice_button_disabled {
            get {
                object obj = ResourceManager.GetObject("customerservice_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customerservice_button_hover {
            get {
                object obj = ResourceManager.GetObject("customerservice_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customerservice_button_normal {
            get {
                object obj = ResourceManager.GetObject("customerservice_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataconversion_button_depressed {
            get {
                object obj = ResourceManager.GetObject("dataconversion_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataconversion_button_disabled {
            get {
                object obj = ResourceManager.GetObject("dataconversion_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataconversion_button_hover {
            get {
                object obj = ResourceManager.GetObject("dataconversion_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataconversion_button_normal {
            get {
                object obj = ResourceManager.GetObject("dataconversion_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap employeemodules_button_depressed {
            get {
                object obj = ResourceManager.GetObject("employeemodules_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap employeemodules_button_disabled {
            get {
                object obj = ResourceManager.GetObject("employeemodules_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap employeemodules_button_hover {
            get {
                object obj = ResourceManager.GetObject("employeemodules_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap employeemodules_button_normal {
            get {
                object obj = ResourceManager.GetObject("employeemodules_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorhandler_button_depressed {
            get {
                object obj = ResourceManager.GetObject("errorhandler_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorhandler_button_disabled {
            get {
                object obj = ResourceManager.GetObject("errorhandler_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorhandler_button_hover {
            get {
                object obj = ResourceManager.GetObject("errorhandler_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorhandler_button_normal {
            get {
                object obj = ResourceManager.GetObject("errorhandler_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_button {
            get {
                object obj = ResourceManager.GetObject("exit_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_button_small {
            get {
                object obj = ResourceManager.GetObject("exit_button_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extenddepdates_button_depressed {
            get {
                object obj = ResourceManager.GetObject("extenddepdates_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extenddepdates_button_disabled {
            get {
                object obj = ResourceManager.GetObject("extenddepdates_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extenddepdates_button_hover {
            get {
                object obj = ResourceManager.GetObject("extenddepdates_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extenddepdates_button_normal {
            get {
                object obj = ResourceManager.GetObject("extenddepdates_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facilitymaster_button_depressed {
            get {
                object obj = ResourceManager.GetObject("facilitymaster_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facilitymaster_button_disabled {
            get {
                object obj = ResourceManager.GetObject("facilitymaster_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facilitymaster_button_hover {
            get {
                object obj = ResourceManager.GetObject("facilitymaster_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facilitymaster_button_normal {
            get {
                object obj = ResourceManager.GetObject("facilitymaster_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardware_button_depressed {
            get {
                object obj = ResourceManager.GetObject("hardware_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardware_button_disabled {
            get {
                object obj = ResourceManager.GetObject("hardware_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardware_button_hover {
            get {
                object obj = ResourceManager.GetObject("hardware_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardware_button_normal {
            get {
                object obj = ResourceManager.GetObject("hardware_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inqreports_button_depressed {
            get {
                object obj = ResourceManager.GetObject("inqreports_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inqreports_button_disabled {
            get {
                object obj = ResourceManager.GetObject("inqreports_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inqreports_button_hover {
            get {
                object obj = ResourceManager.GetObject("inqreports_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inqreports_button_normal {
            get {
                object obj = ResourceManager.GetObject("inqreports_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lookupldapuser_button_depressed {
            get {
                object obj = ResourceManager.GetObject("lookupldapuser_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lookupldapuser_button_disabled {
            get {
                object obj = ResourceManager.GetObject("lookupldapuser_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lookupldapuser_button_hover {
            get {
                object obj = ResourceManager.GetObject("lookupldapuser_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lookupldapuser_button_normal {
            get {
                object obj = ResourceManager.GetObject("lookupldapuser_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap makormaint_button_depressed {
            get {
                object obj = ResourceManager.GetObject("makormaint_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap makormaint_button_disabled {
            get {
                object obj = ResourceManager.GetObject("makormaint_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap makormaint_button_hover {
            get {
                object obj = ResourceManager.GetObject("makormaint_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap makormaint_button_normal {
            get {
                object obj = ResourceManager.GetObject("makormaint_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manageusersess_button_depressed {
            get {
                object obj = ResourceManager.GetObject("manageusersess_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manageusersess_button_disabled {
            get {
                object obj = ResourceManager.GetObject("manageusersess_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manageusersess_button_hover {
            get {
                object obj = ResourceManager.GetObject("manageusersess_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manageusersess_button_normal {
            get {
                object obj = ResourceManager.GetObject("manageusersess_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markmess_button_depressed {
            get {
                object obj = ResourceManager.GetObject("markmess_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markmess_button_disabled {
            get {
                object obj = ResourceManager.GetObject("markmess_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markmess_button_hover {
            get {
                object obj = ResourceManager.GetObject("markmess_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markmess_button_normal {
            get {
                object obj = ResourceManager.GetObject("markmess_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recautotrans_button_depressed {
            get {
                object obj = ResourceManager.GetObject("recautotrans_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recautotrans_button_disabled {
            get {
                object obj = ResourceManager.GetObject("recautotrans_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recautotrans_button_hover {
            get {
                object obj = ResourceManager.GetObject("recautotrans_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recautotrans_button_normal {
            get {
                object obj = ResourceManager.GetObject("recautotrans_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshpkdata_button_depressed {
            get {
                object obj = ResourceManager.GetObject("refreshpkdata_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshpkdata_button_disabled {
            get {
                object obj = ResourceManager.GetObject("refreshpkdata_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshpkdata_button_hover {
            get {
                object obj = ResourceManager.GetObject("refreshpkdata_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshpkdata_button_normal {
            get {
                object obj = ResourceManager.GetObject("refreshpkdata_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relocatemerch_button_depressed {
            get {
                object obj = ResourceManager.GetObject("relocatemerch_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relocatemerch_button_disabled {
            get {
                object obj = ResourceManager.GetObject("relocatemerch_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relocatemerch_button_hover {
            get {
                object obj = ResourceManager.GetObject("relocatemerch_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relocatemerch_button_normal {
            get {
                object obj = ResourceManager.GetObject("relocatemerch_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removereclock_button_depressed {
            get {
                object obj = ResourceManager.GetObject("removereclock_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removereclock_button_disabled {
            get {
                object obj = ResourceManager.GetObject("removereclock_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removereclock_button_hover {
            get {
                object obj = ResourceManager.GetObject("removereclock_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removereclock_button_normal {
            get {
                object obj = ResourceManager.GetObject("removereclock_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetldap_button_depressed {
            get {
                object obj = ResourceManager.GetObject("resetldap_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetldap_button_disabled {
            get {
                object obj = ResourceManager.GetObject("resetldap_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetldap_button_hover {
            get {
                object obj = ResourceManager.GetObject("resetldap_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetldap_button_normal {
            get {
                object obj = ResourceManager.GetObject("resetldap_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resstagtables_button_depressed {
            get {
                object obj = ResourceManager.GetObject("resstagtables_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resstagtables_button_disabled {
            get {
                object obj = ResourceManager.GetObject("resstagtables_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resstagtables_button_hover {
            get {
                object obj = ResourceManager.GetObject("resstagtables_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resstagtables_button_normal {
            get {
                object obj = ResourceManager.GetObject("resstagtables_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retcheckhandling_button_depressed {
            get {
                object obj = ResourceManager.GetObject("retcheckhandling_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retcheckhandling_button_disabled {
            get {
                object obj = ResourceManager.GetObject("retcheckhandling_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retcheckhandling_button_hover {
            get {
                object obj = ResourceManager.GetObject("retcheckhandling_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retcheckhandling_button_normal {
            get {
                object obj = ResourceManager.GetObject("retcheckhandling_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rolesresources_button_depressed {
            get {
                object obj = ResourceManager.GetObject("rolesresources_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rolesresources_button_disabled {
            get {
                object obj = ResourceManager.GetObject("rolesresources_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rolesresources_button_hover {
            get {
                object obj = ResourceManager.GetObject("rolesresources_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rolesresources_button_normal {
            get {
                object obj = ResourceManager.GetObject("rolesresources_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopadmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("shopadmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopadmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("shopadmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopadmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("shopadmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopadmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("shopadmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopprinters_button_depressed {
            get {
                object obj = ResourceManager.GetObject("shopprinters_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopprinters_button_disabled {
            get {
                object obj = ResourceManager.GetObject("shopprinters_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopprinters_button_hover {
            get {
                object obj = ResourceManager.GetObject("shopprinters_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopprinters_button_normal {
            get {
                object obj = ResourceManager.GetObject("shopprinters_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systemadmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("systemadmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systemadmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("systemadmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systemadmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("systemadmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systemadmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("systemadmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxrates_button_depressed {
            get {
                object obj = ResourceManager.GetObject("taxrates_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxrates_button_disabled {
            get {
                object obj = ResourceManager.GetObject("taxrates_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxrates_button_hover {
            get {
                object obj = ResourceManager.GetObject("taxrates_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxrates_button_normal {
            get {
                object obj = ResourceManager.GetObject("taxrates_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlockuser_button_depressed {
            get {
                object obj = ResourceManager.GetObject("unlockuser_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlockuser_button_disabled {
            get {
                object obj = ResourceManager.GetObject("unlockuser_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlockuser_button_hover {
            get {
                object obj = ResourceManager.GetObject("unlockuser_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlockuser_button_normal {
            get {
                object obj = ResourceManager.GetObject("unlockuser_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatemerchimg_button_depressed {
            get {
                object obj = ResourceManager.GetObject("updatemerchimg_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatemerchimg_button_disabled {
            get {
                object obj = ResourceManager.GetObject("updatemerchimg_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatemerchimg_button_hover {
            get {
                object obj = ResourceManager.GetObject("updatemerchimg_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatemerchimg_button_normal {
            get {
                object obj = ResourceManager.GetObject("updatemerchimg_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatenextnum_button_depressed {
            get {
                object obj = ResourceManager.GetObject("updatenextnum_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatenextnum_button_disabled {
            get {
                object obj = ResourceManager.GetObject("updatenextnum_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatenextnum_button_hover {
            get {
                object obj = ResourceManager.GetObject("updatenextnum_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updatenextnum_button_normal {
            get {
                object obj = ResourceManager.GetObject("updatenextnum_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradmin_button_depressed {
            get {
                object obj = ResourceManager.GetObject("useradmin_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradmin_button_disabled {
            get {
                object obj = ResourceManager.GetObject("useradmin_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradmin_button_hover {
            get {
                object obj = ResourceManager.GetObject("useradmin_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradmin_button_normal {
            get {
                object obj = ResourceManager.GetObject("useradmin_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vendormaint_button_depressed {
            get {
                object obj = ResourceManager.GetObject("vendormaint_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vendormaint_button_disabled {
            get {
                object obj = ResourceManager.GetObject("vendormaint_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vendormaint_button_hover {
            get {
                object obj = ResourceManager.GetObject("vendormaint_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vendormaint_button_normal {
            get {
                object obj = ResourceManager.GetObject("vendormaint_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voidtransactions_button_depressed {
            get {
                object obj = ResourceManager.GetObject("voidtransactions_button_depressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voidtransactions_button_disabled {
            get {
                object obj = ResourceManager.GetObject("voidtransactions_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voidtransactions_button_hover {
            get {
                object obj = ResourceManager.GetObject("voidtransactions_button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voidtransactions_button_normal {
            get {
                object obj = ResourceManager.GetObject("voidtransactions_button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
